#!/bin/bash
sudo apt install 0trace
sudo apt install aapt
sudo apt install acccheck
sudo apt install accountsservice
sudo apt install ace-voip
sudo apt install acl
sudo apt install adduser
sudo apt install adwaita-icon-theme
sudo apt install afflib-tools
sudo apt install aglfn
sudo apt install aircrack-ng
sudo apt install albatross-gtk-theme
sudo apt install alsa-tools
sudo apt install amap
sudo apt install amd64-microcode
sudo apt install anacron
sudo apt install android-framework-res
sudo apt install android-libaapt
sudo apt install android-libandroidfw
sudo apt install android-libbacktrace
sudo apt install android-libbase
sudo apt install android-libcutils
sudo apt install android-liblog
sudo apt install android-libunwind
sudo apt install android-libutils
sudo apt install android-libziparchive
sudo apt install apache-users
sudo apt install apache2
sudo apt install apache2-bin
sudo apt install apache2-data
sudo apt install apache2-utils
sudo apt install apg
sudo apt install apktool
sudo apt install apparmor
sudo apt install appstream
sudo apt install apt
sudo apt install apt-listchanges
sudo apt install apt-utils
sudo apt install arj
sudo apt install armitage
sudo apt install arp-scan
sudo apt install arpwatch
sudo apt install asleap
sudo apt install aspell
sudo apt install aspell-en
sudo apt install at-spi2-core
sudo apt install atftpd
sudo apt install atmel-firmware
sudo apt install attr
sudo apt install automater
sudo apt install autopsy
sudo apt install avahi-daemon
sudo apt install axel
sudo apt install b43-fwcutter
sudo apt install backdoor-factory
sudo apt install baobab
sudo apt install base-files
sudo apt install base-passwd
sudo apt install bash
sudo apt install bash-completion
sudo apt install bbqsql
sudo apt install bdfproxy
sudo apt install bed
sudo apt install beef-xss
sudo apt install bind9-host
sudo apt install binfmt-support
sudo apt install binutils
sudo apt install binutils-common:amd64
sudo apt install binutils-x86-64-linux-gnu
sudo apt install binwalk
sudo apt install blackbird-gtk-theme
sudo apt install blindelephant
sudo apt install blt
sudo apt install bluebird-gtk-theme
sudo apt install bluelog
sudo apt install blueranger
sudo apt install bluesnarfer
sudo apt install bluez
sudo apt install bluez-firmware
sudo apt install bluez-hcidump
sudo apt install bluez-obexd
sudo apt install braa
sudo apt install bsdmainutils
sudo apt install bsdutils
sudo apt install btscanner
sudo apt install bubblewrap
sudo apt install build-essential
sudo apt install bulk-extractor
sudo apt install bully
sudo apt install bundler
sudo apt install burpsuite
sudo apt install busybox
sudo apt install bzip2
sudo apt install ca-certificates
sudo apt install ca-certificates-java
sudo apt install cabextract
sudo apt install cadaver
sudo apt install caribou
sudo apt install cdpsnarf
sudo apt install cewl
sudo apt install cgpt
sudo apt install cheese-common
sudo apt install chirp
sudo apt install chkrootkit
sudo apt install chntpw
sudo apt install chrome-gnome-shell
sudo apt install cisco-auditing-tool
sudo apt install cisco-global-exploiter
sudo apt install cisco-ocs
sudo apt install cisco-torch
sudo apt install clang
sudo apt install clang-3.9
sudo apt install clang-4.0
sudo apt install clusterd
sudo apt install cmospwd
sudo apt install colord
sudo apt install colord-data
sudo apt install commix
sudo apt install console-setup
sudo apt install console-setup-linux
sudo apt install copy-router-config
sudo apt install coreutils
sudo apt install couchdb
sudo apt install cowpatty
sudo apt install cpio
sudo apt install cpp
sudo apt install cpp-7
sudo apt install cracklib-runtime
sudo apt install cramfsswap
sudo apt install crda
sudo apt install creddump
sudo apt install cron
sudo apt install crunch
sudo apt install cryptcat
sudo apt install cryptsetup
sudo apt install cryptsetup-bin
sudo apt install cups-bsd
sudo apt install cups-client
sudo apt install cups-common
sudo apt install cups-pk-helper
sudo apt install curl
sudo apt install curlftpfs
sudo apt install cutycapt
sudo apt install cymothoa
sudo apt install dahdi-firmware-nonfree
sudo apt install darkstat
sudo apt install dash
sudo apt install davtest
sudo apt install dbd
sudo apt install dbus
sudo apt install dbus-user-session
sudo apt install dbus-x11
sudo apt install dc3dd
sudo apt install dcfldd
sudo apt install dconf-cli
sudo apt install dconf-gsettings-backend:amd64
sudo apt install dconf-service
sudo apt install dcraw
sudo apt install ddrescue
sudo apt install debconf
sudo apt install debconf-i18n
sudo apt install debian-archive-keyring
sudo apt install debian-faq
sudo apt install debianutils
sudo apt install deblaze
sudo apt install debtags
sudo apt install default-java-plugin
sudo apt install default-jdk
sudo apt install default-jdk-headless
sudo apt install default-jre
sudo apt install default-jre-headless
sudo apt install default-mysql-server
sudo apt install desktop-base
sudo apt install desktop-file-utils
sudo apt install dex2jar
sudo apt install dh-python
sudo apt install dhcpig
sudo apt install dictionaries-common
sudo apt install diffutils
sudo apt install dirb
sudo apt install dirbuster
sudo apt install dirmngr
sudo apt install distro-info-data
sudo apt install dkms
sudo apt install dleyna-server
sudo apt install dmeventd
sudo apt install dmidecode
sudo apt install dmitry
sudo apt install dmsetup
sudo apt install dnmap
sudo apt install dns-root-data
sudo apt install dns2tcp
sudo apt install dnschef
sudo apt install dnsenum
sudo apt install dnsmap
sudo apt install dnsmasq-base
sudo apt install dnsrecon
sudo apt install dnstracer
sudo apt install dnsutils
sudo apt install dnswalk
sudo apt install doc-base
sudo apt install doc-debian
sudo apt install docutils-common
sudo apt install docutils-doc
sudo apt install doona
sudo apt install dos2unix
sudo apt install dosfstools
sudo apt install dotdotpwn
sudo apt install dpkg
sudo apt install dpkg-dev
sudo apt install dradis
sudo apt install driftnet
sudo apt install dsniff
sudo apt install dumpzilla
sudo apt install dwarfdump
sudo apt install e2fslibs:amd64
sudo apt install e2fsprogs
sudo apt install eapmd5pass
sudo apt install easy-rsa
sudo apt install eatmydata
sudo apt install edb-debugger
sudo apt install edb-debugger-plugins:amd64
sudo apt install eject
sudo apt install emacsen-common
sudo apt install enchant
sudo apt install enum4linux
sudo apt install enumiax
sudo apt install eog
sudo apt install erlang17-asn1
sudo apt install erlang17-base
sudo apt install erlang17-crypto
sudo apt install erlang17-eunit
sudo apt install erlang17-inets
sudo apt install erlang17-mnesia
sudo apt install erlang17-os-mon
sudo apt install erlang17-public-key
sudo apt install erlang17-runtime-tools
sudo apt install erlang17-snmp
sudo apt install erlang17-ssl
sudo apt install erlang17-syntax-tools
sudo apt install erlang17-tools
sudo apt install erlang17-webtool
sudo apt install erlang17-xmerl
sudo apt install espeak-ng-data:amd64
sudo apt install ethtool
sudo apt install ettercap-common
sudo apt install ettercap-graphical
sudo apt install evince
sudo apt install evince-common
sudo apt install evolution-data-server
sudo apt install evolution-data-server-common
sudo apt install ewf-tools
sudo apt install exe2hexbat
sudo apt install exfat-fuse
sudo apt install exfat-utils
sudo apt install exif
sudo apt install exim4-base
sudo apt install exim4-config
sudo apt install exim4-daemon-light
sudo apt install exiv2
sudo apt install expect
sudo apt install exploitdb
sudo apt install extundelete
sudo apt install fakeroot
sudo apt install fastjar
sudo apt install fcrackzip
sudo apt install fdisk
sudo apt install fern-wifi-cracker
sudo apt install fierce
sudo apt install fiked
sudo apt install file
sudo apt install file-roller
sudo apt install fimap
sudo apt install findmyhash
sudo apt install findutils
sudo apt install finger
sudo apt install firebird3.0-common
sudo apt install firebird3.0-common-doc
sudo apt install firefox-esr
sudo apt install firmware-amd-graphics
sudo apt install firmware-ath9k-htc
sudo apt install firmware-atheros
sudo apt installer firmware-b43-sudo
sudo apt installer firmware-b43legacy-sudo
sudo apt install firmware-bnx2
sudo apt install firmware-bnx2x
sudo apt install firmware-brcm80211
sudo apt install firmware-cavium
sudo apt install firmware-intel-sound
sudo apt install firmware-intelwimax
sudo apt install firmware-ipw2x00
sudo apt install firmware-ivtv
sudo apt install firmware-iwlwifi
sudo apt install firmware-libertas
sudo apt install firmware-linux
sudo apt install firmware-linux-free
sudo apt install firmware-linux-nonfree
sudo apt install firmware-misc-nonfree
sudo apt install firmware-myricom
sudo apt install firmware-netxen
sudo apt install firmware-qlogic
sudo apt install firmware-realtek
sudo apt install firmware-samsung
sudo apt install firmware-siano
sudo apt install firmware-ti-connectivity
sudo apt install firmware-zd1211
sudo apt install flac
sudo apt install flasm
sudo apt install flex
sudo apt install florence
sudo apt install folks-common
sudo apt install fontconfig
sudo apt install fontconfig-config
sudo apt install fonts-cantarell
sudo apt install fonts-dejavu
sudo apt install fonts-dejavu-core
sudo apt install fonts-dejavu-extra
sudo apt install fonts-droid-fallback
sudo apt install fonts-lato
sudo apt install fonts-liberation
sudo apt install fonts-lmodern
sudo apt install fonts-lyx
sudo apt install fonts-noto-mono
sudo apt install fonts-texgyre
sudo apt install fonts-wine
sudo apt install foremost
sudo apt install fping
sudo apt install fragroute
sudo apt install fragrouter
sudo apt install framework2
sudo apt install freeglut3:amd64
sudo apt install freepats
sudo apt install freetds-common
sudo apt install ftester
sudo apt install funkload
sudo apt install fuse
sudo apt install g++
sudo apt install g++-7
sudo apt install galera-3
sudo apt install galleta
sudo apt install gawk
sudo apt install gcc
sudo apt install gcc-6-base:amd64
sudo apt install gcc-7
sudo apt install gcc-7-base:amd64
sudo apt install gcr
sudo apt install gdal-bin
sudo apt install gdal-data
sudo apt install gdb
sudo apt install gdisk
sudo apt install gdm3
sudo apt install gedit
sudo apt install gedit-common
sudo apt install genisoimage
sudo apt install geoclue-2.0
sudo apt install geoip-database
sudo apt install geoip-database-extra
sudo apt install gettext-base
sudo apt install ghost-phisher
sudo apt install ghostscript
sudo apt install gir1.2-accountsservice-1.0
sudo apt install gir1.2-atk-1.0:amd64
sudo apt install gir1.2-atspi-2.0:amd64
sudo apt install gir1.2-caribou-1.0
sudo apt install gir1.2-clutter-1.0:amd64
sudo apt install gir1.2-clutter-gst-3.0:amd64
sudo apt install gir1.2-cogl-1.0:amd64
sudo apt install gir1.2-coglpango-1.0:amd64
sudo apt install gir1.2-evince-3.0:amd64
sudo apt install gir1.2-freedesktop:amd64
sudo apt install gir1.2-gck-1:amd64
sudo apt install gir1.2-gcr-3:amd64
sudo apt install gir1.2-gdesktopenums-3.0:amd64
sudo apt install gir1.2-gdkpixbuf-2.0:amd64
sudo apt install gir1.2-gdm-1.0:amd64
sudo apt install gir1.2-geoclue-2.0:amd64
sudo apt install gir1.2-glib-2.0:amd64
sudo apt install gir1.2-gmenu-3.0:amd64
sudo apt install gir1.2-gnomebluetooth-1.0:amd64
sudo apt install gir1.2-gnomedesktop-3.0:amd64
sudo apt install gir1.2-gnomekeyring-1.0
sudo apt install gir1.2-gst-plugins-base-1.0
sudo apt install gir1.2-gstreamer-1.0
sudo apt install gir1.2-gtk-3.0:amd64
sudo apt install gir1.2-gtkclutter-1.0:amd64
sudo apt install gir1.2-gtksource-3.0:amd64
sudo apt install gir1.2-gweather-3.0:amd64
sudo apt install gir1.2-ibus-1.0:amd64
sudo apt install gir1.2-javascriptcoregtk-4.0:amd64
sudo apt install gir1.2-json-1.0:amd64
sudo apt install gir1.2-mutter-1:amd64
sudo apt install gir1.2-networkmanager-1.0:amd64
sudo apt install gir1.2-nmgtk-1.0:amd64
sudo apt install gir1.2-notify-0.7:amd64
sudo apt install gir1.2-packagekitglib-1.0
sudo apt install gir1.2-pango-1.0:amd64
sudo apt install gir1.2-peas-1.0:amd64
sudo apt install gir1.2-polkit-1.0
sudo apt install gir1.2-rsvg-2.0:amd64
sudo apt install gir1.2-soup-2.4:amd64
sudo apt install gir1.2-totem-1.0:amd64
sudo apt install gir1.2-totemplparser-1.0:amd64
sudo apt install gir1.2-upowerglib-1.0:amd64
sudo apt install gir1.2-vte-2.91:amd64
sudo apt install gir1.2-webkit2-4.0:amd64
sudo apt install gir1.2-wnck-3.0:amd64
sudo apt install giskismet
sudo apt install git
sudo apt install git-man
sudo apt install gjs
sudo apt install gkbd-capplet
sudo apt install glib-networking:amd64
sudo apt install glib-networking-common
sudo apt install glib-networking-services
sudo apt install glusterfs-common
sudo apt install gnome-accessibility-themes
sudo apt install gnome-backgrounds
sudo apt install gnome-bluetooth
sudo apt install gnome-brave-icon-theme
sudo apt install gnome-calculator
sudo apt install gnome-characters
sudo apt install gnome-colors-common
sudo apt install gnome-contacts
sudo apt install gnome-control-center
sudo apt install gnome-control-center-data
sudo apt install gnome-core
sudo apt install gnome-desktop3-data
sudo apt install gnome-disk-utility
sudo apt install gnome-font-viewer
sudo apt install gnome-icon-theme
sudo apt install gnome-keyring
sudo apt install gnome-logs
sudo apt install gnome-menus
sudo apt install gnome-online-accounts
sudo apt install gnome-online-miners
sudo apt install gnome-orca
sudo apt install gnome-session
sudo apt install gnome-session-bin
sudo apt install gnome-session-common
sudo apt install gnome-settings-daemon
sudo apt install gnome-shell
sudo apt install gnome-shell-common
sudo apt install gnome-shell-extension-dashtodock
sudo apt install gnome-shell-extension-easyscreencast
sudo apt install gnome-shell-extension-proxyswitcher
sudo apt install gnome-shell-extension-workspacestodock
sudo apt install gnome-shell-extensions
sudo apt install gnome-software
sudo apt install gnome-software-common
sudo apt install gnome-sushi
sudo apt install gnome-system-monitor
sudo apt install gnome-terminal
sudo apt install gnome-terminal-data
sudo apt install gnome-theme-kali
sudo apt install gnome-themes-standard:amd64
sudo apt install gnome-themes-standard-data
sudo apt install gnome-tweak-tool
sudo apt install gnome-user-docs
sudo apt install gnome-user-share
sudo apt install gnupg
sudo apt install gnupg-l10n
sudo apt install gnupg-utils
sudo apt install gnuplot
sudo apt install gnuplot-data
sudo apt install gnuplot-qt
sudo apt install gnutls-bin
sudo apt install golismero
sudo apt install gparted
sudo apt install gpg
sudo apt install gpg-agent
sudo apt install gpg-wks-client
sudo apt install gpg-wks-server
sudo apt install gpgconf
sudo apt install gpgsm
sudo apt install gpgv
sudo apt install gpp-decrypt
sudo apt install grabber
sudo apt install greenbone-security-assistant
sudo apt install greenbone-security-assistant-common
sudo apt install grep
sudo apt install greybird-gtk-theme
sudo apt install grilo-plugins-0.3:amd64
sudo apt install groff-base
sudo apt install grub-common
sudo apt install grub-pc
sudo apt install grub-pc-bin
sudo apt install grub2-common
sudo apt install gsettings-desktop-schemas
sudo apt install gsfonts
sudo apt install gsfonts-x11
sudo apt install gstreamer1.0-clutter-3.0:amd64
sudo apt install gstreamer1.0-libav:amd64
sudo apt install gstreamer1.0-packagekit
sudo apt install gstreamer1.0-plugins-bad:amd64
sudo apt install gstreamer1.0-plugins-base:amd64
sudo apt install gstreamer1.0-plugins-good:amd64
sudo apt install gstreamer1.0-plugins-ugly:amd64
sudo apt install gstreamer1.0-pulseaudio:amd64
sudo apt install gstreamer1.0-x:amd64
sudo apt install gtk-update-icon-cache
sudo apt install gtk2-engines-murrine:amd64
sudo apt install gtk2-engines-pixbuf:amd64
sudo apt install guile-2.0-libs:amd64
sudo apt install guymager
sudo apt install gvfs:amd64
sudo apt install gvfs-backends
sudo apt install gvfs-bin
sudo apt install gvfs-common
sudo apt install gvfs-daemons
sudo apt install gvfs-fuse
sudo apt install gvfs-libs:amd64
sudo apt install gzip
sudo apt install hackrf
sudo apt install hamster-sidejack
sudo apt install hash-identifier
sudo apt install hashcat
sudo apt install hashcat-data
sudo apt install hashcat-utils
sudo apt install hashdeep
sudo apt install hashid
sudo apt install hdmi2usb-fx2-firmware
sudo apt install hdparm
sudo apt install hexinject
sudo apt install hexorbase
sudo apt install hicolor-icon-theme
sudo apt install hostname
sudo apt install hotpatch
sudo apt install hping3
sudo apt install httrack
sudo apt install hunspell-en-us
sudo apt install hydra
sudo apt install hydra-gtk
sudo apt install hyperion
sudo apt install i2c-tools
sudo apt install i965-va-driver:amd64
sudo apt install iaxflood
sudo apt install ibverbs-providers:amd64
sudo apt install icedtea-8-plugin:amd64
sudo apt install icedtea-netx:amd64
sudo apt install icedtea-netx-common
sudo apt install ieee-data
sudo apt install ifenslave
sudo apt install ifupdown
sudo apt install iio-sensor-proxy
sudo apt install ike-scan
sudo apt install imagemagick
sudo apt install imagemagick-6-common
sudo apt install imagemagick-6.q16
sudo apt install inetsim
sudo apt install init
sudo apt install init-system-helpers
sudo apt install initramfs-tools
sudo apt install initramfs-tools-core
sudo apt install intel-microcode
sudo apt install intersect
sudo apt install intrace
sudo apt install inviteflood
sudo apt install iodine
sudo apt install iproute2
sudo apt install iptables
sudo apt install iputils-arping
sudo apt install iputils-ping
sudo apt install ipxe-qemu
sudo apt install ipython
sudo apt install irpas
sudo apt install irqbalance
sudo apt install isc-dhcp-client
sudo apt install isc-dhcp-common
sudo apt install isc-dhcp-server
sudo apt install iso-codes
sudo apt install iucode-tool
sudo apt install iw
sudo apt install ixo-usb-jtag
sudo apt install jad
sudo apt install jarwrapper
sudo apt install java-common
sudo apt install java-wrappers
sudo apt install javascript-common
sudo apt install javasnoop
sudo apt install jboss-autopwn
sudo apt install john
sudo apt install john-data
sudo apt install johnny
sudo apt install joomscan
sudo apt install jsql-injection
sudo apt install junit
sudo apt install kali-archive-keyring
sudo apt install kali-debtags
sudo apt install kali-defaults
sudo apt install kali-desktop-common
sudo apt install kali-desktop-gnome
sudo apt install kali-desktop-live
sudo apt install kali-linux
sudo apt install kali-linux-full
sudo apt install kali-menu
sudo apt install kali-root-login
sudo apt install kbd
sudo apt install keepnote
sudo apt install keimpx
sudo apt install keyboard-configuration
sudo apt install killerbee
sudo apt install king-phisher
sudo apt install kismet
sudo apt install klibc-utils
sudo apt install kmod
sudo apt install krb5-locales
sudo apt install laudanum
sudo apt install lbd
sudo apt install ldap-utils
sudo apt install leafpad
sudo apt install less
sudo apt install liba52-0.7.4:amd64
sudo apt install libaa1:amd64
sudo apt install libaacs0:amd64
sudo apt install libaccountsservice0:amd64
sudo apt install libacl1:amd64
sudo apt install libacl1-dev
sudo apt install libadns1
sudo apt install libaec0:amd64
sudo apt install libafflib0v5
sudo apt install libaio1:amd64
sudo apt install libalgorithm-c3-perl
sudo apt install libalgorithm-diff-perl
sudo apt install libalgorithm-diff-xs-perl
sudo apt install libalgorithm-merge-perl
sudo apt install libantlr-java
sudo apt install libantlr3-runtime-java
sudo apt install libao-common
sudo apt install libao4
sudo apt install libapache-pom-java
sudo apt install libapache2-mod-dnssd
sudo apt install libapache2-mod-php7.0
sudo apt install libapparmor1:amd64
sudo apt install libappstream-glib8:amd64
sudo apt install libappstream4:amd64
sudo apt install libapr1:amd64
sudo apt install libaprutil1:amd64
sudo apt install libaprutil1-dbd-sqlite3:amd64
sudo apt install libaprutil1-ldap:amd64
sudo apt install libapt-inst2.0:amd64
sudo apt install libapt-pkg5.0:amd64
sudo apt install libarchive13:amd64
sudo apt install libarmadillo8
sudo apt install libarpack2:amd64
sudo apt install libasan4:amd64
sudo apt install libasound2:amd64
sudo apt install libasound2-data
sudo apt install libasound2-plugins:amd64
sudo apt install libaspell15:amd64
sudo apt install libass9:amd64
sudo apt install libassuan0:amd64
sudo apt install libasyncns0:amd64
sudo apt install libatasmart4:amd64
sudo apt install libatinject-jsr330-api-java
sudo apt install libatk-adaptor:amd64
sudo apt install libatk-bridge2.0-0:amd64
sudo apt install libatk-wrapper-java
sudo apt install libatk-wrapper-java-jni:amd64
sudo apt install libatk1.0-0:amd64
sudo apt install libatk1.0-data
sudo apt install libatkmm-1.6-1v5:amd64
sudo apt install libatomic1:amd64
sudo apt install libatspi2.0-0:amd64
sudo apt install libattr1:amd64
sudo apt install libattr1-dev:amd64
sudo apt install libaudio2:amd64
sudo apt install libaudit-common
sudo apt install libaudit1:amd64
sudo apt install libauthen-sasl-perl
sudo apt install libavahi-client3:amd64
sudo apt install libavahi-common-data:amd64
sudo apt install libavahi-common3:amd64
sudo apt install libavahi-core7:amd64
sudo apt install libavahi-glib1:amd64
sudo apt install libavahi-gobject0:amd64
sudo apt install libavc1394-0:amd64
sudo apt install libavcodec57:amd64
sudo apt install libavfilter6:amd64
sudo apt install libavformat57:amd64
sudo apt install libavresample3:amd64
sudo apt install libavutil55:amd64
sudo apt install libb-hooks-endofscope-perl
sudo apt install libb-hooks-op-check-perl
sudo apt install libbabeltrace-ctf1
sudo apt install libbabeltrace1:amd64
sudo apt install libbdplus0:amd64
sudo apt install libbfio1
sudo apt install libbind9-160:amd64
sudo apt install libbinutils:amd64
sudo apt install libblas3:amd64
sudo apt install libblkid1:amd64
sudo apt install libblockdev-crypto2:amd64
sudo apt install libblockdev-fs2:amd64
sudo apt install libblockdev-loop2:amd64
sudo apt install libblockdev-part-err2:amd64
sudo apt install libblockdev-part2:amd64
sudo apt install libblockdev-swap2:amd64
sudo apt install libblockdev-utils2:amd64
sudo apt install libblockdev2:amd64
sudo apt install libbluetooth-dev:amd64
sudo apt install libbluetooth3:amd64
sudo apt install libbluray2:amd64
sudo apt install libboost-date-time1.62.0:amd64
sudo apt install libboost-filesystem1.62.0:amd64
sudo apt install libboost-iostreams1.62.0:amd64
sudo apt install libboost-random1.62.0:amd64
sudo apt install libboost-system1.62.0:amd64
sudo apt install libboost-thread1.62.0:amd64
sudo apt install libbrlapi0.6:amd64
sudo apt install libbs2b0:amd64
sudo apt install libbsd0:amd64
sudo apt install libbytes-random-secure-perl
sudo apt install libbz2-1.0:amd64
sudo apt install libc-ares2:amd64
sudo apt install libc-bin
sudo apt install libc-dev-bin
sudo apt install libc-l10n
sudo apt install libc6:amd64
sudo apt install libc6-dbg:amd64
sudo apt install libc6-dev:amd64
sudo apt install libcaca0:amd64
sudo apt install libcacard0:amd64
sudo apt install libcairo-gobject2:amd64
sudo apt install libcairo-perl
sudo apt install libcairo2:amd64
sudo apt install libcairomm-1.0-1v5:amd64
sudo apt install libcamel-1.2-60:amd64
sudo apt install libcanberra-gtk-module:amd64
sudo apt install libcanberra-gtk0:amd64
sudo apt install libcanberra-gtk3-0:amd64
sudo apt install libcanberra-gtk3-module:amd64
sudo apt install libcanberra-pulse:amd64
sudo apt install libcanberra0:amd64
sudo apt install libcap-ng0:amd64
sudo apt install libcap2:amd64
sudo apt install libcap2-bin
sudo apt install libcapstone3
sudo apt install libcaribou-common
sudo apt install libcaribou0:amd64
sudo apt install libcc1-0:amd64
sudo apt install libccid
sudo apt install libcdio-cdda2:amd64
sudo apt install libcdio-paranoia2:amd64
sudo apt install libcdio17:amd64
sudo apt install libcdparanoia0:amd64
sudo apt install libcdt5
sudo apt install libcephfs1
sudo apt install libcgi-fast-perl
sudo apt install libcgi-pm-perl
sudo apt install libcgraph6
sudo apt install libchamplain-0.12-0:amd64
sudo apt install libcharls1:amd64
sudo apt install libcheese-gtk25:amd64
sudo apt install libcheese8:amd64
sudo apt install libchromaprint1:amd64
sudo apt install libcilkrts5:amd64
sudo apt install libclang-common-3.9-dev
sudo apt install libclang-common-4.0-dev
sudo apt install libclang1-3.9:amd64
sudo apt install libclang1-4.0:amd64
sudo apt install libclass-c3-perl
sudo apt install libclass-c3-xs-perl
sudo apt install libclass-isa-perl
sudo apt install libclass-load-perl
sudo apt install libclass-load-xs-perl
sudo apt install libclass-tiny-perl
sudo apt install libcli1.9:amd64
sudo apt install libclutter-1.0-0:amd64
sudo apt install libclutter-1.0-common
sudo apt install libclutter-gst-3.0-0:amd64
sudo apt install libclutter-gtk-1.0-0:amd64
sudo apt install libcogl-common
sudo apt install libcogl-pango20:amd64
sudo apt install libcogl-path20:amd64
sudo apt install libcogl20:amd64
sudo apt install libcolord-gtk1:amd64
sudo apt install libcolord2:amd64
sudo apt install libcolorhug2:amd64
sudo apt install libcomerr2:amd64
sudo apt install libcommons-cli-java
sudo apt install libcommons-io-java
sudo apt install libcommons-lang3-java
sudo apt install libcommons-parent-java
sudo apt install libconfig-inifiles-perl
sudo apt install libconfig9:amd64
sudo apt install libcrack2:amd64
sudo apt install libcroco3:amd64
sudo apt install libcrypt-random-seed-perl
sudo apt install libcrypt-ssleay-perl
sudo apt install libcryptsetup4:amd64
sudo apt install libcrystalhd3:amd64
sudo apt install libct4:amd64
sudo apt install libcue1
sudo apt install libcups2:amd64
sudo apt install libcupsfilters1:amd64
sudo apt install libcupsimage2:amd64
sudo apt install libcurl3:amd64
sudo apt install libcurl3-gnutls:amd64
sudo apt install libdaemon0:amd64
sudo apt install libdap25:amd64
sudo apt install libdapclient6v5:amd64
sudo apt install libdapserver7v5:amd64
sudo apt install libdata-dump-perl
sudo apt install libdata-optlist-perl
sudo apt install libdate-manip-perl
sudo apt install libdatrie1:amd64
sudo apt install libdb5.3:amd64
sudo apt install libdbd-mysql-perl
sudo apt install libdbd-sqlite3-perl
sudo apt install libdbi-perl
sudo apt install libdbus-1-3:amd64
sudo apt install libdbus-glib-1-2:amd64
sudo apt install libdc1394-22:amd64
sudo apt install libdca0:amd64
sudo apt install libdconf1:amd64
sudo apt install libde265-0:amd64
sudo apt install libdebconfclient0:amd64
sudo apt install libdee-1.0-4
sudo apt install libdevel-callchecker-perl
sudo apt install libdevel-caller-perl
sudo apt install libdevel-globaldestruction-perl
sudo apt install libdevel-lexalias-perl
sudo apt install libdevel-overloadinfo-perl
sudo apt install libdevel-partialdump-perl
sudo apt install libdevel-stacktrace-perl
sudo apt install libdevmapper-event1.02.1:amd64
sudo apt install libdevmapper1.02.1:amd64
sudo apt install libdigest-crc-perl
sudo apt install libdigest-hmac-perl
sudo apt install libdigest-md4-perl
sudo apt install libdigest-md5-file-perl
sudo apt install libdist-checkconflicts-perl
sudo apt install libdistorm3-3
sudo apt install libdjvulibre-text
sudo apt install libdjvulibre21:amd64
sudo apt install libdleyna-connector-dbus-1.0-1:amd64
sudo apt install libdleyna-core-1.0-3:amd64
sudo apt install libdmapsharing-3.0-2:amd64
sudo apt install libdns-export1100
sudo apt install libdns-export169
sudo apt install libdns169:amd64
sudo apt install libdotconf0:amd64
sudo apt install libdouble-conversion1:amd64
sudo apt install libdpkg-perl
sudo apt install libdrm-amdgpu1:amd64
sudo apt install libdrm-common
sudo apt install libdrm-dev:amd64
sudo apt install libdrm-intel1:amd64
sudo apt install libdrm-nouveau2:amd64
sudo apt install libdrm-radeon1:amd64
sudo apt install libdrm2:amd64
sudo apt install libdumbnet1:amd64
sudo apt install libdv4:amd64
sudo apt install libdvdnav4:amd64
sudo apt install libdvdread4:amd64
sudo apt install libdw1:amd64
sudo apt install libdynaloader-functions-perl
sudo apt install libeatmydata1:amd64
sudo apt install libebackend-1.2-10:amd64
sudo apt install libebook-1.2-19:amd64
sudo apt install libebook-contacts-1.2-2:amd64
sudo apt install libecal-1.2-19:amd64
sudo apt install libedata-book-1.2-25:amd64
sudo apt install libedata-cal-1.2-28:amd64
sudo apt install libedataserver-1.2-22:amd64
sudo apt install libedataserverui-1.2-1:amd64
sudo apt install libedit2:amd64
sudo apt install libegl-mesa0:amd64
sudo apt install libegl1:amd64
sudo apt install libelf1:amd64
sudo apt install libenca0:amd64
sudo apt install libenchant1c2a:amd64
sudo apt install libencode-locale-perl
sudo apt install libepoxy0:amd64
sudo apt install libepsilon1:amd64
sudo apt install liberror-perl
sudo apt install libespeak-ng1:amd64
sudo apt install libestr0:amd64
sudo apt install libeval-closure-perl
sudo apt install libevdev2:amd64
sudo apt install libevdocument3-4:amd64
sudo apt install libevent-2.1-6:amd64
sudo apt install libevent-core-2.1-6:amd64
sudo apt install libevent-openssl-2.1-6:amd64
sudo apt install libevent-pthreads-2.1-6:amd64
sudo apt install libevview3-3:amd64
sudo apt install libewf2
sudo apt install libexempi3:amd64
sudo apt install libexif12:amd64
sudo apt install libexiv2-14:amd64
sudo apt install libexpat1:amd64
sudo apt install libexpat1-dev:amd64
sudo apt install libfaad2:amd64
sudo apt install libfabric1
sudo apt install libfakeroot:amd64
sudo apt install libfastjson4:amd64
sudo apt install libfbclient2:amd64
sudo apt install libfcgi-bin
sudo apt install libfcgi-perl
sudo apt install libfcgi0ldbl:amd64
sudo apt install libfdisk1:amd64
sudo apt install libfdt1:amd64
sudo apt install libffi-dev:amd64
sudo apt install libffi6:amd64
sudo apt install libfftw3-double3:amd64
sudo apt install libfftw3-single3:amd64
sudo apt install libfile-basedir-perl
sudo apt install libfile-copy-recursive-perl
sudo apt install libfile-desktopentry-perl
sudo apt install libfile-fcntllock-perl
sudo apt install libfile-listing-perl
sudo apt install libfile-mimeinfo-perl
sudo apt install libfindrtp
sudo apt install libfl-dev:amd64
sudo apt install libflac8:amd64
sudo apt install libflite1:amd64
sudo apt install libflorence-1.0-1:amd64
sudo apt install libfluidsynth1:amd64
sudo apt install libfolks-eds25:amd64
sudo apt install libfolks-telepathy25:amd64
sudo apt install libfolks25:amd64
sudo apt install libfont-afm-perl
sudo apt install libfontconfig1:amd64
sudo apt install libfontenc1:amd64
sudo apt install libfreefare-bin
sudo apt install libfreefare0:amd64
sudo apt install libfreerdp-cache1.1:amd64
sudo apt install libfreerdp-client1.1:amd64
sudo apt install libfreerdp-codec1.1:amd64
sudo apt install libfreerdp-common1.1.0:amd64
sudo apt install libfreerdp-core1.1:amd64
sudo apt install libfreerdp-crypto1.1:amd64
sudo apt install libfreerdp-gdi1.1:amd64
sudo apt install libfreerdp-locale1.1:amd64
sudo apt install libfreerdp-primitives1.1:amd64
sudo apt install libfreerdp-utils1.1:amd64
sudo apt install libfreetype6:amd64
sudo apt install libfreexl1:amd64
sudo apt install libfribidi0:amd64
sudo apt install libfuse2:amd64
sudo apt install libfwupd2:amd64
sudo apt install libfyba0:amd64
sudo apt install libgail-3-0:amd64
sudo apt install libgail-common:amd64
sudo apt install libgail18:amd64
sudo apt install libgbm1:amd64
sudo apt install libgc1c2:amd64
sudo apt install libgcab-1.0-0:amd64
sudo apt install libgcc-7-dev:amd64
sudo apt install libgcc1:amd64
sudo apt install libgck-1-0:amd64
sudo apt install libgcr-3-common
sudo apt install libgcr-base-3-1:amd64
sudo apt install libgcr-ui-3-1:amd64
sudo apt install libgcrypt20:amd64
sudo apt install libgd3:amd64
sudo apt install libgdal20
sudo apt install libgdata-common
sudo apt install libgdata22:amd64
sudo apt install libgdbm3:amd64
sudo apt install libgdcm2.8:amd64
sudo apt install libgdk-pixbuf2.0-0:amd64
sudo apt install libgdk-pixbuf2.0-bin
sudo apt install libgdk-pixbuf2.0-common
sudo apt install libgdm1
sudo apt install libgee-0.8-2:amd64
sudo apt install libgeoclue-2-0:amd64
sudo apt install libgeocode-glib0:amd64
sudo apt install libgeoip1:amd64
sudo apt install libgeos-3.6.2:amd64
sudo apt install libgeos-c1v5:amd64
sudo apt install libgeotiff2:amd64
sudo apt install libgfbgraph-0.2-0:amd64
sudo apt install libgfortran4:amd64
sudo apt install libgif7:amd64
sudo apt install libgirepository-1.0-1:amd64
sudo apt install libgjs0g
sudo apt install libgl1:amd64
sudo apt install libgl1-mesa-dev:amd64
sudo apt install libgl1-mesa-dri:amd64
sudo apt install libgl1-mesa-glx:amd64
sudo apt install libgl2ps1.4
sudo apt install libglade2-0:amd64
sudo apt install libglapi-mesa:amd64
sudo apt install libgles2:amd64
sudo apt install libglib-perl
sudo apt install libglib2.0-0:amd64
sudo apt install libglib2.0-bin
sudo apt install libglib2.0-data
sudo apt install libglibmm-2.4-1v5:amd64
sudo apt install libglu1-mesa:amd64
sudo apt install libglu1-mesa-dev:amd64
sudo apt install libglvnd-core-dev:amd64
sudo apt install libglvnd-dev:amd64
sudo apt install libglvnd0:amd64
sudo apt install libglx-mesa0:amd64
sudo apt install libglx0:amd64
sudo apt install libgme0:amd64
sudo apt install libgmime-3.0-0:amd64
sudo apt install libgmp-dev:amd64
sudo apt install libgmp10:amd64
sudo apt install libgmpxx4ldbl:amd64
sudo apt install libgnome-autoar-0-0:amd64
sudo apt install libgnome-bluetooth13:amd64
sudo apt install libgnome-desktop-3-12:amd64
sudo apt install libgnome-keyring-common
sudo apt install libgnome-keyring0:amd64
sudo apt install libgnome-menu-3-0:amd64
sudo apt install libgnomekbd-common
sudo apt install libgnomekbd8:amd64
sudo apt install libgnutls-dane0:amd64
sudo apt install libgnutls30:amd64
sudo apt install libgoa-1.0-0b:amd64
sudo apt install libgoa-1.0-common
sudo apt install libgoa-backend-1.0-1:amd64
sudo apt install libgom-1.0-0:amd64
sudo apt install libgomp1:amd64
sudo apt install libgpg-error0:amd64
sudo apt install libgpgme11:amd64
sudo apt install libgphoto2-6:amd64
sudo apt install libgphoto2-l10n
sudo apt install libgphoto2-port12:amd64
sudo apt install libgpm2:amd64
sudo apt install libgraphite2-3:amd64
sudo apt install libgrilo-0.3-0:amd64
sudo apt install libgs9:amd64
sudo apt install libgs9-common
sudo apt install libgsasl7
sudo apt install libgsf-1-114:amd64
sudo apt install libgsf-1-common
sudo apt install libgsm1:amd64
sudo apt install libgspell-1-1:amd64
sudo apt install libgspell-1-common
sudo apt install libgssapi-krb5-2:amd64
sudo apt install libgssdp-1.0-3:amd64
sudo apt install libgssglue1:amd64
sudo apt install libgstreamer-plugins-bad1.0-0:amd64
sudo apt install libgstreamer-plugins-base1.0-0:amd64
sudo apt install libgstreamer1.0-0:amd64
sudo apt install libgtk-3-0:amd64
sudo apt install libgtk-3-bin
sudo apt install libgtk-3-common
sudo apt install libgtk2-perl
sudo apt install libgtk2.0-0:amd64
sudo apt install libgtk2.0-bin
sudo apt install libgtk2.0-common
sudo apt install libgtkmm-2.4-1v5:amd64
sudo apt install libgtkmm-3.0-1v5:amd64
sudo apt install libgtksourceview-3.0-1:amd64
sudo apt install libgtksourceview-3.0-common
sudo apt install libgtop-2.0-11:amd64
sudo apt install libgtop2-common
sudo apt install libgts-0.7-5:amd64
sudo apt install libgts-bin
sudo apt install libguava-java
sudo apt install libgudev-1.0-0:amd64
sudo apt install libgupnp-1.0-4:amd64
sudo apt install libgupnp-av-1.0-2
sudo apt install libgupnp-dlna-2.0-3
sudo apt install libgusb2:amd64
sudo apt install libguytools2
sudo apt install libgvc6
sudo apt install libgweather-3-6:amd64
sudo apt install libgweather-common
sudo apt install libgxps2:amd64
sudo apt install libhackrf0:amd64
sudo apt install libharfbuzz-icu0:amd64
sudo apt install libharfbuzz0b:amd64
sudo apt install libhdf4-0-alt
sudo apt install libhdf5-100:amd64
sudo apt install libhdf5-openmpi-100:amd64
sudo apt install libhiredis0.13:amd64
sudo apt install libhivex-bin
sudo apt install libhivex0:amd64
sudo apt install libhogweed4:amd64
sudo apt install libhtml-form-perl
sudo apt install libhtml-format-perl
sudo apt install libhtml-linkextractor-perl
sudo apt install libhtml-parser-perl
sudo apt install libhtml-tagset-perl
sudo apt install libhtml-template-perl
sudo apt install libhtml-tree-perl
sudo apt install libhttp-cookies-perl
sudo apt install libhttp-daemon-perl
sudo apt install libhttp-date-perl
sudo apt install libhttp-dav-perl
sudo apt install libhttp-message-perl
sudo apt install libhttp-negotiate-perl
sudo apt install libhttp-parser2.7.1:amd64
sudo apt install libhttp-server-simple-perl
sudo apt install libhttrack2
sudo apt install libhunspell-1.6-0:amd64
sudo apt install libhwloc-plugins
sudo apt install libhwloc5:amd64
sudo apt install libhyphen0:amd64
sudo apt install libi2c0:amd64
sudo apt install libibus-1.0-5:amd64
sudo apt install libibverbs1:amd64
sudo apt install libical3:amd64
sudo apt install libice-dev:amd64
sudo apt install libice6:amd64
sudo apt install libicu-le-hb0:amd64
sudo apt install libicu57:amd64
sudo apt install libicu60:amd64
sudo apt install libidn11:amd64
sudo apt install libidn2-0:amd64
sudo apt install libiec61883-0:amd64
sudo apt install libieee1284-3:amd64
sudo apt install libijs-0.35:amd64
sudo apt install libilmbase23:amd64
sudo apt install libimobiledevice6:amd64
sudo apt install libinput-bin
sudo apt install libinput10:amd64
sudo apt install libio-all-lwp-perl
sudo apt install libio-all-perl
sudo apt install libio-html-perl
sudo apt install libio-multiplex-perl
sudo apt install libio-socket-inet6-perl
sudo apt install libio-socket-socks-perl
sudo apt install libio-socket-ssl-perl
sudo apt install libip4tc0:amd64
sudo apt install libip6tc0:amd64
sudo apt install libipc-shareable-perl
sudo apt install libipc-system-simple-perl
sudo apt install libiptc0:amd64
sudo apt install libiptcdata0
sudo apt install libirs-export160
sudo apt install libisc-export166:amd64
sudo apt install libisc-export169:amd64
sudo apt install libisc166:amd64
sudo apt install libisccc160:amd64
sudo apt install libisccfg-export160
sudo apt install libisccfg160:amd64
sudo apt install libisl15:amd64
sudo apt install libitm1:amd64
sudo apt install libiw30:amd64
sudo apt install libjack-jackd2-0:amd64
sudo apt install libjansson4:amd64
sudo apt install libjavascriptcoregtk-4.0-18:amd64
sudo apt install libjaxp1.3-java
sudo apt install libjbig0:amd64
sudo apt install libjbig2dec0:amd64
sudo apt install libjemalloc1
sudo apt install libjim0.77:amd64
sudo apt install libjpeg-turbo-progs
sudo apt install libjpeg62-turbo:amd64
sudo apt install libjs-excanvas
sudo apt install libjs-jquery
sudo apt install libjs-jquery-easing
sudo apt install libjs-jquery-fancybox
sudo apt install libjs-jquery-form
sudo apt install libjs-jquery-mousewheel
sudo apt install libjs-jquery-ui
sudo apt install libjs-openlayers
sudo apt install libjs-source-map
sudo apt install libjs-sphinxdoc
sudo apt install libjs-uglify
sudo apt install libjs-underscore
sudo apt install libjson-c3:amd64
sudo apt install libjson-glib-1.0-0:amd64
sudo apt install libjson-glib-1.0-common
sudo apt install libjsoncpp1:amd64
sudo apt install libjsr305-java
sudo apt install libjudydebian1
sudo apt install libjxr-tools
sudo apt install libjxr0:amd64
sudo apt install libk5crypto3:amd64
sudo apt install libkate1:amd64
sudo apt install libkeyutils1:amd64
sudo apt install libklibc
sudo apt install libkmlbase1:amd64
sudo apt install libkmlconvenience1:amd64
sudo apt install libkmldom1:amd64
sudo apt install libkmlengine1:amd64
sudo apt install libkmlregionator1:amd64
sudo apt install libkmlxsd1:amd64
sudo apt install libkmod2:amd64
sudo apt install libkpathsea6:amd64
sudo apt install libkrb5-3:amd64
sudo apt install libkrb5support0:amd64
sudo apt install libksba8:amd64
sudo apt install libkyotocabinet16v5:amd64
sudo apt install liblapack3:amd64
sudo apt install liblcms2-2:amd64
sudo apt install libldap-2.4-2:amd64
sudo apt install libldap-common
sudo apt install libldb1:amd64
sudo apt install liblept5
sudo apt install liblilv-0-0
sudo apt install liblinear3:amd64
sudo apt install liblirc-client0:amd64
sudo apt install libllvm3.9:amd64
sudo apt install libllvm4.0:amd64
sudo apt install libllvm5.0:amd64
sudo apt install liblocale-gettext-perl
sudo apt install liblockfile-bin
sudo apt install liblog4cpp5v5
sudo apt install liblogging-stdlog0:amd64
sudo apt install liblognorm5:amd64
sudo apt install liblouis-data
sudo apt install liblouis14:amd64
sudo apt install liblqr-1-0:amd64
sudo apt install liblsan0:amd64
sudo apt install libltdl7:amd64
sudo apt install liblua5.2-0:amd64
sudo apt install liblua5.3-0:amd64
sudo apt install libluajit-5.1-2:amd64
sudo apt install libluajit-5.1-common
sudo apt install liblvm2app2.2:amd64
sudo apt install liblvm2cmd2.02:amd64
sudo apt install liblwgeom-2.4-0
sudo apt install liblwgeom-dev
sudo apt install liblwp-mediatypes-perl
sudo apt install liblwp-protocol-https-perl
sudo apt install liblwp-protocol-socks-perl
sudo apt install liblwres160:amd64
sudo apt install liblz4-1:amd64
sudo apt install liblzma5:amd64
sudo apt install liblzo2-2:amd64
sudo apt install libmagic-dev:amd64
sudo apt install libmagic-mgc
sudo apt install libmagic1:amd64
sudo apt install libmagickcore-6.q16-3:amd64
sudo apt install libmagickcore-6.q16-3-extra:amd64
sudo apt install libmagickwand-6.q16-3:amd64
sudo apt install libmailtools-perl
sudo apt install libmailutils5:amd64
sudo apt install libmariadbclient18:amd64
sudo apt install libmath-random-isaac-perl
sudo apt install libmath-random-isaac-xs-perl
sudo apt install libmaxminddb0:amd64
sudo apt install libmbim-glib4:amd64
sudo apt install libmbim-proxy
sudo apt install libmdb2:amd64
sudo apt install libmdbsql2:amd64
sudo apt install libmediaart-2.0-0:amd64
sudo apt install libmicrohttpd12
sudo apt install libminiupnpc17:amd64
sudo apt install libminizip1:amd64
sudo apt install libmjpegutils-2.1-0
sudo apt install libmm-glib0:amd64
sudo apt install libmms0:amd64
sudo apt install libmng1:amd64
sudo apt install libmnl0:amd64
sudo apt install libmodplug1:amd64
sudo apt install libmodule-implementation-perl
sudo apt install libmodule-runtime-conflicts-perl
sudo apt install libmodule-runtime-perl
sudo apt install libmoose-perl
sudo apt install libmosquitto1:amd64
sudo apt install libmotif-common
sudo apt install libmount1:amd64
sudo apt install libmozjs-52-0:amd64
sudo apt install libmozjs185-1.0
sudo apt install libmp3lame0:amd64
sudo apt install libmpc3:amd64
sudo apt install libmpcdec6:amd64
sudo apt install libmpdec2:amd64
sudo apt install libmpeg2-4:amd64
sudo apt install libmpeg2encpp-2.1-0
sudo apt install libmpfr4:amd64
sudo apt install libmpfr6:amd64
sudo apt install libmpg123-0:amd64
sudo apt install libmplex2-2.1-0
sudo apt install libmpx2:amd64
sudo apt install libmro-compat-perl
sudo apt install libmspack0:amd64
sudo apt install libmtdev1:amd64
sudo apt install libmtp-common
sudo apt install libmtp-runtime
sudo apt install libmtp9:amd64
sudo apt install libmusicbrainz5-2:amd64
sudo apt install libmusicbrainz5cc2v5:amd64
sudo apt install libmutter-1-0:amd64
sudo apt install libmysofa0:amd64
sudo apt install libnamespace-clean-perl
sudo apt install libnautilus-extension1a:amd64
sudo apt install libncurses5:amd64
sudo apt install libncursesw5:amd64
sudo apt install libndp0:amd64
sudo apt install libneon27-gnutls:amd64
sudo apt install libnet-cidr-perl
sudo apt install libnet-dbus-perl
sudo apt install libnet-dns-perl
sudo apt install libnet-http-perl
sudo apt install libnet-ip-perl
sudo apt install libnet-netmask-perl
sudo apt install libnet-pcap-perl
sudo apt install libnet-rawip-perl
sudo apt install libnet-server-perl
sudo apt install libnet-smtp-ssl-perl
sudo apt install libnet-snmp-perl
sudo apt install libnet-ssh2-perl
sudo apt install libnet-ssleay-perl
sudo apt install libnet-telnet-perl
sudo apt install libnet-tftp-perl
sudo apt install libnet1:amd64
sudo apt install libnetcdf-c++4
sudo apt install libnetcdf13:amd64
sudo apt install libnetfilter-conntrack3:amd64
sudo apt install libnetfilter-queue1
sudo apt install libnetpacket-perl
sudo apt install libnetpbm10
sudo apt install libnettle6:amd64
sudo apt install libnewt0.52:amd64
sudo apt install libnfc-bin
sudo apt install libnfc5:amd64
sudo apt install libnfnetlink0:amd64
sudo apt install libnfs8:amd64
sudo apt install libnghttp2-14:amd64
sudo apt install libnginx-mod-http-auth-pam
sudo apt install libnginx-mod-http-dav-ext
sudo apt install libnginx-mod-http-echo
sudo apt install libnginx-mod-http-geoip
sudo apt install libnginx-mod-http-image-filter
sudo apt install libnginx-mod-http-subs-filter
sudo apt install libnginx-mod-http-upstream-fair
sudo apt install libnginx-mod-http-xslt-filter
sudo apt install libnginx-mod-mail
sudo apt install libnginx-mod-stream
sudo apt install libnids1.21:amd64
sudo apt install libnl-3-200:amd64
sudo apt install libnl-genl-3-200:amd64
sudo apt install libnl-route-3-200:amd64
sudo apt install libnm-glib4:amd64
sudo apt install libnm-gtk0:amd64
sudo apt install libnm-util2:amd64
sudo apt install libnm0:amd64
sudo apt install libnma0:amd64
sudo apt install libnorm1:amd64
sudo apt install libnotify-bin
sudo apt install libnotify4:amd64
sudo apt install libnpth0:amd64
sudo apt install libnspr4:amd64
sudo apt install libnss-mdns:amd64
sudo apt install libnss-myhostname:amd64
sudo apt install libnss3:amd64
sudo apt install libntfs-3g88
sudo apt install libntlm0:amd64
sudo apt install libnuma1:amd64
sudo apt install libnumber-bytes-human-perl
sudo apt install liboauth0:amd64
sudo apt install libobjc-7-dev:amd64
sudo apt install libobjc4:amd64
sudo apt install libodbc1:amd64
sudo apt install libofa0:amd64
sudo apt install libogdi3.2
sudo apt install libogg0:amd64
sudo apt install libopenal-data
sudo apt install libopenal1:amd64
sudo apt install libopencore-amrnb0:amd64
sudo apt install libopencore-amrwb0:amd64
sudo apt install libopencv-calib3d3.2:amd64
sudo apt install libopencv-contrib3.2:amd64
sudo apt install libopencv-core3.2:amd64
sudo apt install libopencv-features2d3.2:amd64
sudo apt install libopencv-flann3.2:amd64
sudo apt install libopencv-highgui3.2:amd64
sudo apt install libopencv-imgcodecs3.2:amd64
sudo apt install libopencv-imgproc3.2:amd64
sudo apt install libopencv-ml3.2:amd64
sudo apt install libopencv-objdetect3.2:amd64
sudo apt install libopencv-photo3.2:amd64
sudo apt install libopencv-shape3.2:amd64
sudo apt install libopencv-stitching3.2:amd64
sudo apt install libopencv-superres3.2:amd64
sudo apt install libopencv-video3.2:amd64
sudo apt install libopencv-videoio3.2:amd64
sudo apt install libopencv-videostab3.2:amd64
sudo apt install libopencv-viz3.2:amd64
sudo apt install libopenexr22:amd64
sudo apt install libopengl0:amd64
sudo apt install libopenjp2-7:amd64
sudo apt install libopenmpi2:amd64
sudo apt install libopenmpt0:amd64
sudo apt install libopenvas9:amd64
sudo apt install libopts25:amd64
sudo apt install libopus0:amd64
sudo apt install liborc-0.4-0:amd64
sudo apt install libosinfo-1.0-0:amd64
sudo apt install libosmesa6:amd64
sudo apt install libout123-0:amd64
sudo apt install libp11-kit0:amd64
sudo apt install libpackage-deprecationmanager-perl
sudo apt install libpackage-stash-perl
sudo apt install libpackage-stash-xs-perl
sudo apt install libpackagekit-glib2-18:amd64
sudo apt install libpadwalker-perl
sudo apt install libpam-cap:amd64
sudo apt install libpam-gnome-keyring:amd64
sudo apt install libpam-modules:amd64
sudo apt install libpam-modules-bin
sudo apt install libpam-runtime
sudo apt install libpam-systemd:amd64
sudo apt install libpam0g:amd64
sudo apt install libpango-1.0-0:amd64
sudo apt install libpango-perl
sudo apt install libpangocairo-1.0-0:amd64
sudo apt install libpangoft2-1.0-0:amd64
sudo apt install libpangomm-1.4-1v5:amd64
sudo apt install libpangoxft-1.0-0:amd64
sudo apt install libpaper-utils
sudo apt install libpaper1:amd64
sudo apt install libparallel-forkmanager-perl
sudo apt install libparams-classify-perl
sudo apt install libparams-util-perl
sudo apt install libparted-fs-resize0:amd64
sudo apt install libparted2:amd64
sudo apt install libpathplan4
sudo apt install libpcap0.8:amd64
sudo apt install libpcaudio0
sudo apt install libpci3:amd64
sudo apt install libpciaccess0:amd64
sudo apt install libpcre2-16-0:amd64
sudo apt install libpcre2-8-0:amd64
sudo apt install libpcre3:amd64
sudo apt install libpcsc-perl
sudo apt install libpcsclite1:amd64
sudo apt install libpeas-1.0-0:amd64
sudo apt install libpeas-common
sudo apt install libperl5.26:amd64
sudo apt install libpgm-5.2-0:amd64
sudo apt install libphonenumber7:amd64
sudo apt install libpipeline1:amd64
sudo apt install libpixman-1-0:amd64
sudo apt install libpkcs11-helper1:amd64
sudo apt install libplist3:amd64
sudo apt install libpng16-16:amd64
sudo apt install libpocl1:amd64
sudo apt install libpocl1-common
sudo apt install libpolkit-agent-1-0:amd64
sudo apt install libpolkit-backend-1-0:amd64
sudo apt install libpolkit-gobject-1-0:amd64
sudo apt install libpoppler-glib8:amd64
sudo apt install libpoppler68:amd64
sudo apt install libpoppler72:amd64
sudo apt install libpopt0:amd64
sudo apt install libportaudio2:amd64
sudo apt install libpostproc54:amd64
sudo apt install libpotrace0
sudo apt install libpq5:amd64
sudo apt install libprocps6:amd64
sudo apt install libproj12:amd64
sudo apt install libprotobuf-lite10:amd64
sudo apt install libprotobuf10:amd64
sudo apt install libproxy1-plugin-gsettings:amd64
sudo apt install libproxy1-plugin-networkmanager:amd64
sudo apt install libproxy1v5:amd64
sudo apt install libproxychains3:amd64
sudo apt install libpsl5:amd64
sudo apt install libpsm-infinipath1
sudo apt install libpst4:amd64
sudo apt install libptexenc1:amd64
sudo apt install libpthread-stubs0-dev:amd64
sudo apt install libpulse-mainloop-glib0:amd64
sudo apt install libpulse0:amd64
sudo apt install libpulsedsp:amd64
sudo apt install libpwquality-common
sudo apt install libpwquality1:amd64
sudo apt install libpyside1.2:amd64
sudo apt install libpython-all-dev:amd64
sudo apt install libpython-dev:amd64
sudo apt install libpython-stdlib:amd64
sudo apt install libpython2.7:amd64
sudo apt install libpython2.7-dev:amd64
sudo apt install libpython2.7-minimal:amd64
sudo apt install libpython2.7-stdlib:amd64
sudo apt install libpython3-stdlib:amd64
sudo apt install libpython3.6:amd64
sudo apt install libpython3.6-minimal:amd64
sudo apt install libpython3.6-stdlib:amd64
sudo apt install libqca2:amd64
sudo apt install libqca2-plugins:amd64
sudo apt install libqgis-analysis2.14.21
sudo apt install libqgis-core2.14.21
sudo apt install libqgis-customwidgets
sudo apt install libqgis-gui2.14.21
sudo apt install libqgis-networkanalysis2.14.21
sudo apt install libqgis-server2.14.21
sudo apt install libqgispython2.14.21
sudo apt install libqhull7:amd64
sudo apt install libqmi-glib5:amd64
sudo apt install libqmi-proxy
sudo apt install libqscintilla2-qt4-13
sudo apt install libqscintilla2-qt4-l10n
sudo apt install libqscintilla2-qt5-13
sudo apt install libqscintilla2-qt5-l10n
sudo apt install libqt4-dbus:amd64
sudo apt install libqt4-declarative:amd64
sudo apt install libqt4-designer:amd64
sudo apt install libqt4-dev
sudo apt install libqt4-dev-bin
sudo apt install libqt4-help:amd64
sudo apt install libqt4-network:amd64
sudo apt install libqt4-opengl:amd64
sudo apt install libqt4-opengl-dev
sudo apt install libqt4-qt3support:amd64
sudo apt install libqt4-script:amd64
sudo apt install libqt4-scripttools:amd64
sudo apt install libqt4-sql:amd64
sudo apt install libqt4-sql-mysql:amd64
sudo apt install libqt4-svg:amd64
sudo apt install libqt4-test:amd64
sudo apt install libqt4-xml:amd64
sudo apt install libqt4-xmlpatterns:amd64
sudo apt install libqt5concurrent5:amd64
sudo apt install libqt5core5a:amd64
sudo apt install libqt5dbus5:amd64
sudo apt install libqt5gui5:amd64
sudo apt install libqt5multimedia5:amd64
sudo apt install libqt5network5:amd64
sudo apt install libqt5positioning5:amd64
sudo apt install libqt5printsupport5:amd64
sudo apt install libqt5qml5:amd64
sudo apt install libqt5quick5:amd64
sudo apt install libqt5sensors5:amd64
sudo apt install libqt5svg5:amd64
sudo apt install libqt5test5:amd64
sudo apt install libqt5webchannel5:amd64
sudo apt install libqt5webkit5:amd64
sudo apt install libqt5widgets5:amd64
sudo apt install libqt5xml5:amd64
sudo apt install libqt5xmlpatterns5:amd64
sudo apt install libqtassistantclient4:amd64
sudo apt install libqtcore4:amd64
sudo apt install libqtdbus4:amd64
sudo apt install libqtgui4:amd64
sudo apt install libqtwebkit4:amd64
sudo apt install libquadmath0:amd64
sudo apt install libquvi-0.9-0.9.3:amd64
sudo apt install libquvi-scripts-0.9
sudo apt install libqwt5-qt4
sudo apt install libqwt6abi1
sudo apt install libradare2-2.1:amd64
sudo apt install libradare2-common
sudo apt install libradare2-dev
sudo apt install libradcli4
sudo apt install libraw1394-11:amd64
sudo apt install librdmacm1:amd64
sudo apt install libreadline5:amd64
sudo apt install libreadline7:amd64
sudo apt install libregfi1
sudo apt install librest-0.7-0:amd64
sudo apt install librsvg2-2:amd64
sudo apt install librsvg2-common:amd64
sudo apt install librtmp1:amd64
sudo apt install librubberband2:amd64
sudo apt install libruby2.3:amd64
sudo apt install librygel-core-2.6-2
sudo apt install librygel-db-2.6-2
sudo apt install librygel-renderer-2.6-2
sudo apt install librygel-server-2.6-2
sudo apt install libsamplerate0:amd64
sudo apt install libsane:amd64
sudo apt install libsane-common
sudo apt install libsane-extras:amd64
sudo apt install libsane-extras-common
sudo apt install libsasl2-2:amd64
sudo apt install libsasl2-modules:amd64
sudo apt install libsasl2-modules-db:amd64
sudo apt install libsbc1:amd64
sudo apt install libsctp1:amd64
sudo apt install libseccomp2:amd64
sudo apt install libsecret-1-0:amd64
sudo apt install libsecret-common
sudo apt install libselinux1:amd64
sudo apt install libsemanage-common
sudo apt install libsemanage1:amd64
sudo apt install libsensors4:amd64
sudo apt install libsepol1:amd64
sudo apt install libserd-0-0:amd64
sudo apt install libserf-1-1:amd64
sudo apt install libshiboken1.2v5:amd64
sudo apt install libshine3:amd64
sudo apt install libshout3:amd64
sudo apt install libsidplay1v5
sudo apt install libsigc++-2.0-0v5:amd64
sudo apt install libsigsegv2:amd64
sudo apt install libslang2:amd64
sudo apt install libsm-dev:amd64
sudo apt install libsm6:amd64
sudo apt install libsmali-java
sudo apt install libsmartcols1:amd64
sudo apt install libsmbclient:amd64
sudo apt install libsmi2ldbl:amd64
sudo apt install libsnappy1v5:amd64
sudo apt install libsndfile1:amd64
sudo apt install libsndio6.1:amd64
sudo apt install libsnmp-base
sudo apt install libsnmp-perl
sudo apt install libsnmp30:amd64
sudo apt install libsocket++1:amd64
sudo apt install libsocket6-perl
sudo apt install libsodium23:amd64
sudo apt install libsonic0:amd64
sudo apt install libsord-0-0:amd64
sudo apt install libsoundtouch1:amd64
sudo apt install libsoup-gnome2.4-1:amd64
sudo apt install libsoup2.4-1:amd64
sudo apt install libsoxr0:amd64
sudo apt install libspandsp2:amd64
sudo apt install libspatialindex4v5:amd64
sudo apt install libspatialite7:amd64
sudo apt install libspectre1:amd64
sudo apt install libspeechd2:amd64
sudo apt install libspeex1:amd64
sudo apt install libspeexdsp1:amd64
sudo apt install libspice-server1:amd64
sudo apt install libspiffy-perl
sudo apt install libsqlite3-0:amd64
sudo apt install libsratom-0-0:amd64
sudo apt install libsrtp0
sudo apt install libss2:amd64
sudo apt install libssh-4:amd64
sudo apt install libssh-gcrypt-4:amd64
sudo apt install libssh2-1:amd64
sudo apt install libssl1.0.2:amd64
sudo apt install libssl1.1:amd64
sudo apt install libstartup-notification0:amd64
sudo apt install libstdc++-7-dev:amd64
sudo apt install libstdc++6:amd64
sudo apt install libstemmer0d:amd64
sudo apt install libstring-random-perl
sudo apt install libstringtemplate-java
sudo apt install libsub-exporter-perl
sudo apt install libsub-exporter-progressive-perl
sudo apt install libsub-identify-perl
sudo apt install-perl libsub-sudo
sudo apt install libsub-name-perl
sudo apt install libsuperlu5:amd64
sudo apt install libsvn1:amd64
sudo apt install libswitch-perl
sudo apt install libswresample2:amd64
sudo apt install libswscale4:amd64
sudo apt install libsybdb5:amd64
sudo apt install libsynctex2:amd64
sudo apt install libsystemd0:amd64
sudo apt install libsz2:amd64
sudo apt install libtag1v5:amd64
sudo apt install libtag1v5-vanilla:amd64
sudo apt install libtagc0:amd64
sudo apt install libtalloc2:amd64
sudo apt install libtasn1-6:amd64
sudo apt install libtbb2:amd64
sudo apt install libtcl8.5:amd64
sudo apt install libtcl8.6:amd64
sudo apt install libtdb1:amd64
sudo apt install libteamdctl0:amd64
sudo apt install libtelepathy-glib0:amd64
sudo apt install libterm-readkey-perl
sudo apt install libterm-readline-gnu-perl
sudo apt install libtesseract4
sudo apt install libtevent0:amd64
sudo apt install libtexlua52:amd64
sudo apt install libtexlua53:amd64
sudo apt install libtexluajit2:amd64
sudo apt install libtext-charwidth-perl
sudo apt install libtext-iconv-perl
sudo apt install libtext-wrapi18n-perl
sudo apt install libthai-data
sudo apt install libthai0:amd64
sudo apt install libtheora0:amd64
sudo apt install libtidy5
sudo apt install libtie-ixhash-perl
sudo apt install libtiff5:amd64
sudo apt install libtimedate-perl
sudo apt install libtinfo-dev:amd64
sudo apt install libtinfo5:amd64
sudo apt install libtk8.5:amd64
sudo apt install libtk8.6:amd64
sudo apt install libtommath1:amd64
sudo apt install libtotem-plparser-common
sudo apt install libtotem-plparser18:amd64
sudo apt install libtotem0:amd64
sudo apt install libtracker-control-2.0-0:amd64
sudo apt install libtracker-miner-2.0-0:amd64
sudo apt install libtracker-sparql-2.0-0:amd64
sudo apt install libtry-tiny-perl
sudo apt install libtsan0:amd64
sudo apt install libtsk13
sudo apt install libturbojpeg0:amd64
sudo apt install libtwolame0:amd64
sudo apt install libtxc-dxtn-s2tc:amd64
sudo apt install libubsan0:amd64
sudo apt install libucl1:amd64
sudo apt install libudev1:amd64
sudo apt install libudisks2-0:amd64
sudo apt install libunbound2:amd64
sudo apt install libunistring2:amd64
sudo apt install libupower-glib3:amd64
sudo apt install liburcu6:amd64
sudo apt install liburi-perl
sudo apt install liburiparser1:amd64
sudo apt install libusb-0.1-4:amd64
sudo apt install libusb-1.0-0:amd64
sudo apt install libusbmuxd4:amd64
sudo apt install libusbredirparser1:amd64
sudo apt install libutempter0:amd64
sudo apt install libuuid-perl
sudo apt install libuuid1:amd64
sudo apt install libuv1:amd64
sudo apt install libv4l-0:amd64
sudo apt install libv4lconvert0:amd64
sudo apt install libva-drm2:amd64
sudo apt install libva-x11-2:amd64
sudo apt install libva2:amd64
sudo apt install libvariable-magic-perl
sudo apt install libvdeplug2
sudo apt install libvdpau-va-gl1:amd64
sudo apt install libvdpau1:amd64
sudo apt install libvisual-0.4-0:amd64
sudo apt install libvo-aacenc0:amd64
sudo apt install libvo-amrwbenc0:amd64
sudo apt install libvolume-key1
sudo apt install libvorbis0a:amd64
sudo apt install libvorbisenc2:amd64
sudo apt install libvorbisfile3:amd64
sudo apt install libvpx4:amd64
sudo apt install libvte-2.91-0:amd64
sudo apt install libvte-2.91-common
sudo apt install libvtk6.3
sudo apt install libvulkan1:amd64
sudo apt install libwacom-bin
sudo apt install libwacom-common
sudo apt install libwacom2:amd64
sudo apt install libwavpack1:amd64
sudo apt install libwayland-client0:amd64
sudo apt install libwayland-cursor0:amd64
sudo apt install libwayland-egl1-mesa:amd64
sudo apt install libwayland-server0:amd64
sudo apt install libwbclient0:amd64
sudo apt install libwebkit2gtk-4.0-37:amd64
sudo apt install libwebp6:amd64
sudo apt install libwebpdemux2:amd64
sudo apt install libwebpmux3:amd64
sudo apt install libwebrtc-audio-processing1:amd64
sudo apt install libwhisker2-perl
sudo apt install libwildmidi-config
sudo apt install libwildmidi2:amd64
sudo apt install libwine:amd64
sudo apt install libwinpr-crt0.1:amd64
sudo apt install libwinpr-crypto0.1:amd64
sudo apt install libwinpr-dsparse0.1:amd64
sudo apt install libwinpr-environment0.1:amd64
sudo apt install libwinpr-file0.1:amd64
sudo apt install libwinpr-handle0.1:amd64
sudo apt install libwinpr-heap0.1:amd64
sudo apt install libwinpr-input0.1:amd64
sudo apt install libwinpr-interlocked0.1:amd64
sudo apt install libwinpr-library0.1:amd64
sudo apt install libwinpr-path0.1:amd64
sudo apt install libwinpr-pool0.1:amd64
sudo apt install libwinpr-registry0.1:amd64
sudo apt install libwinpr-rpc0.1:amd64
sudo apt install libwinpr-sspi0.1:amd64
sudo apt install libwinpr-synch0.1:amd64
sudo apt install libwinpr-sysinfo0.1:amd64
sudo apt install libwinpr-thread0.1:amd64
sudo apt install libwinpr-utils0.1:amd64
sudo apt install libwireshark-data
sudo apt install libwireshark10:amd64
sudo apt install libwiretap7:amd64
sudo apt install libwmf0.2-7:amd64
sudo apt install libwnck-3-0:amd64
sudo apt install libwnck-3-common
sudo apt install libwrap0:amd64
sudo apt install libwscodecs1:amd64
sudo apt install libwsutil8:amd64
sudo apt install libwww-mechanize-perl
sudo apt install libwww-perl
sudo apt install libwww-robotrules-perl
sudo apt install libwxbase3.0-0v5:amd64
sudo apt install libwxgtk3.0-0v5:amd64
sudo apt install libx11-6:amd64
sudo apt install libx11-data
sudo apt install libx11-dev:amd64
sudo apt install libx11-doc
sudo apt install libx11-protocol-perl
sudo apt install libx11-xcb-dev:amd64
sudo apt install libx11-xcb1:amd64
sudo apt install libx264-148:amd64
sudo apt install libx265-146:amd64
sudo apt install libx86-1:amd64
sudo apt install libxapian30:amd64
sudo apt install libxatracker2:amd64
sudo apt install libxau-dev:amd64
sudo apt install libxau6:amd64
sudo apt install libxaw7:amd64
sudo apt install libxcb-dri2-0:amd64
sudo apt install libxcb-dri2-0-dev:amd64
sudo apt install libxcb-dri3-0:amd64
sudo apt install libxcb-dri3-dev:amd64
sudo apt install libxcb-glx0:amd64
sudo apt install libxcb-glx0-dev:amd64
sudo apt install libxcb-icccm4:amd64
sudo apt install libxcb-image0:amd64
sudo apt install libxcb-keysyms1:amd64
sudo apt install libxcb-present-dev:amd64
sudo apt install libxcb-present0:amd64
sudo apt install libxcb-randr0:amd64
sudo apt install libxcb-randr0-dev:amd64
sudo apt install libxcb-render-util0:amd64
sudo apt install libxcb-render0:amd64
sudo apt install libxcb-render0-dev:amd64
sudo apt install libxcb-res0:amd64
sudo apt install libxcb-shape0:amd64
sudo apt install libxcb-shape0-dev:amd64
sudo apt install libxcb-shm0:amd64
sudo apt install libxcb-sync-dev:amd64
sudo apt install libxcb-sync1:amd64
sudo apt install libxcb-util0:amd64
sudo apt install libxcb-xf86dri0:amd64
sudo apt install libxcb-xfixes0:amd64
sudo apt install libxcb-xfixes0-dev:amd64
sudo apt install libxcb-xinerama0:amd64
sudo apt install libxcb-xkb1:amd64
sudo apt install libxcb-xv0:amd64
sudo apt install libxcb1:amd64
sudo apt install libxcb1-dev:amd64
sudo apt install libxcomposite1:amd64
sudo apt install libxcursor1:amd64
sudo apt install libxdamage-dev:amd64
sudo apt install libxdamage1:amd64
sudo apt install libxdmcp-dev:amd64
sudo apt install libxdmcp6:amd64
sudo apt install libxdot4
sudo apt install libxen-4.8:amd64
sudo apt install libxenstore3.0:amd64
sudo apt install libxerces-c3.2:amd64
sudo apt install libxext-dev:amd64
sudo apt install libxext6:amd64
sudo apt install libxfixes-dev:amd64
sudo apt install libxfixes3:amd64
sudo apt install libxfont1:amd64
sudo apt install libxfont2:amd64
sudo apt install libxft2:amd64
sudo apt install libxi6:amd64
sudo apt install libxinerama1:amd64
sudo apt install libxkbcommon-x11-0:amd64
sudo apt install libxkbcommon0:amd64
sudo apt install libxkbfile1:amd64
sudo apt install libxklavier16:amd64
sudo apt install libxm4:amd64
sudo apt install libxml-dom-perl
sudo apt install libxml-libxml-perl
sudo apt install libxml-namespacesupport-perl
sudo apt install libxml-parser-perl
sudo apt install libxml-perl
sudo apt install libxml-regexp-perl
sudo apt install libxml-sax-base-perl
sudo apt install libxml-sax-expat-perl
sudo apt install libxml-sax-perl
sudo apt install libxml-twig-perl
sudo apt install libxml-writer-perl
sudo apt install libxml-xpathengine-perl
sudo apt install libxml2:amd64
sudo apt install libxmlunit-java
sudo apt install libxmu6:amd64
sudo apt install libxmuu1:amd64
sudo apt install libxpm4:amd64
sudo apt install libxpp3-java
sudo apt install libxrandr2:amd64
sudo apt install libxrender1:amd64
sudo apt install libxres1:amd64
sudo apt install libxshmfence-dev:amd64
sudo apt install libxshmfence1:amd64
sudo apt install libxslt1.1:amd64
sudo apt install libxss1:amd64
sudo apt install libxt-dev:amd64
sudo apt install libxt6:amd64
sudo apt install libxtables12:amd64
sudo apt install libxtst6:amd64
sudo apt install libxv1:amd64
sudo apt install libxvidcore4:amd64
sudo apt install libxvmc1:amd64
sudo apt install libxxf86dga1:amd64
sudo apt install libxxf86vm-dev:amd64
sudo apt install libxxf86vm1:amd64
sudo apt install libyajl2:amd64
sudo apt install libyaml-0-2:amd64
sudo apt install libyaml-snake-java
sudo apt install libyaml-tiny-perl
sudo apt install libyara3:amd64
sudo apt install libyelp0:amd64
sudo apt install libzapojit-0.0-0:amd64
sudo apt install libzbar0:amd64
sudo apt install libzeitgeist-2.0-0:amd64
sudo apt install libzip4:amd64
sudo apt install libzmq5:amd64
sudo apt install libzvbi-common
sudo apt install libzvbi0:amd64
sudo apt install libzzip-0-13:amd64
sudo apt install linux-base
sudo apt install linux-compiler-gcc-7-x86
sudo apt install linux-headers-4.14.0-kali3-amd64
sudo apt install linux-headers-4.14.0-kali3-common
sudo apt install linux-headers-amd64
sudo apt install linux-image-4.14.0-kali3-amd64
sudo apt install linux-image-amd64
sudo apt install linux-kbuild-4.14
sudo apt install linux-libc-dev:amd64
sudo apt install llvm-3.9
sudo apt install llvm-3.9-dev
sudo apt install llvm-3.9-runtime
sudo apt install llvm-4.0
sudo apt install llvm-4.0-dev
sudo apt install llvm-4.0-runtime
sudo apt install lmodern
sudo apt install locales
sudo apt install locales-all
sudo apt install login
sudo apt install logrotate
sudo apt install lrzsz
sudo apt install lsb-base
sudo apt install lsb-release
sudo apt install lsof
sudo apt install lua-bitop:amd64
sudo apt install lua-expat:amd64
sudo apt install lua-json
sudo apt install lua-lpeg:amd64
sudo apt install lua-socket:amd64
sudo apt install lvm2
sudo apt install lynis
sudo apt install m4
sudo apt install macchanger
sudo apt install magicrescue
sudo apt install magictree
sudo apt install mailutils
sudo apt install mailutils-common
sudo apt install make
sudo apt install maltego
sudo apt install maltego-teeth
sudo apt install man-db
sudo apt install manpages
sudo apt install manpages-dev
sudo apt install mariadb-client-10.1
sudo apt install mariadb-client-core-10.1
sudo apt install mariadb-common
sudo apt install mariadb-server-10.1
sudo apt install mariadb-server-core-10.1
sudo apt install maskprocessor
sudo apt install masscan
sudo apt install mawk
sudo apt install mc
sudo apt install mc-data
sudo apt install mdbtools
sudo apt install mdk3
sudo apt install medusa
sudo apt install memdump
sudo apt install menu
sudo apt install mercurial
sudo apt install mercurial-common
sudo apt install mesa-common-dev:amd64
sudo apt install mesa-va-drivers:amd64
sudo apt install mesa-vdpau-drivers:amd64
sudo apt install metasploit-framework
sudo apt install mfcuk
sudo apt install mfoc
sudo apt install mfterm
sudo apt install mime-support
sudo apt install mimikatz
sudo apt install minicom
sudo apt install miniupnpc
sudo apt install miranda
sudo apt install miredo
sudo apt install missidentify
sudo apt install mitmproxy
sudo apt install mlocate
sudo apt install mobile-broadband-provider-info
sudo apt install modemmanager
sudo apt install mosquitto-clients
sudo apt install mount
sudo apt install mousetweaks
sudo apt install mpg123
sudo apt install msfpc
sudo apt install mtd-utils
sudo apt install multiarch-support
sudo apt install multimac
sudo apt install murrine-themes
sudo apt install mutter
sudo apt install mutter-common
sudo apt install mysql-common
sudo apt install nano
sudo apt install nasm
sudo apt install nautilus
sudo apt install nautilus-data
sudo apt install nbtscan
sudo apt install ncat-w32
sudo apt install ncompress
sudo apt install ncrack
sudo apt install ncurses-base
sudo apt install ncurses-bin
sudo apt install ncurses-hexedit
sudo apt install ncurses-term
sudo apt install ndiff
sudo apt install net-tools
sudo apt install netbase
sudo apt install netcat-traditional
sudo apt install netdiscover
sudo apt install netmask
sudo apt install netpbm
sudo apt install netsed
sudo apt install netsniff-ng
sudo apt install netwag
sudo apt install network-manager
sudo apt install network-manager-gnome
sudo apt install netwox
sudo apt install nfspy
sudo apt install nginx
sudo apt install nginx-common
sudo apt install nginx-full
sudo apt install ngrep
sudo apt install nikto
sudo apt install nipper-ng
sudo apt install nishang
sudo apt install nmap
sudo apt install nmap-common
sudo apt install nodejs
sudo apt install notification-daemon
sudo apt install ntfs-3g
sudo apt install ntp
sudo apt install ntpdate
sudo apt install ocl-icd-libopencl1:amd64
sudo apt install odbcinst
sudo apt install odbcinst1debian2:amd64
sudo apt install ohrwurm
sudo apt install ollydbg
sudo apt install onesixtyone
sudo apt install openbios-ppc
sudo apt install openbios-sparc
sudo apt install openhackware
sudo apt install openjdk-8-jdk:amd64
sudo apt install openjdk-8-jdk-headless:amd64
sudo apt install openjdk-8-jre:amd64
sudo apt install openjdk-8-jre-headless:amd64
sudo apt install openmpi-bin
sudo apt install openmpi-common
sudo apt install opensc
sudo apt install opensc-pkcs11:amd64
sudo apt install openssh-client
sudo apt install openssh-server
sudo apt install openssh-sftp-server
sudo apt install openssl
sudo apt install openvas
sudo apt install openvas-cli
sudo apt install openvas-manager
sudo apt install openvas-manager-common
sudo apt install openvas-scanner
sudo apt install openvpn
sudo apt install ophcrack
sudo apt install ophcrack-cli
sudo apt install orca
sudo apt install os-prober
sudo apt install oscanner
sudo apt install osinfo-db
sudo apt install osslsigncode
sudo apt install p0f
sudo apt install p11-kit
sudo apt install p11-kit-modules:amd64
sudo apt install p7zip
sudo apt install p7zip-full
sudo apt install pack
sudo apt install packagekit
sudo apt install packagekit-tools
sudo apt install padbuster
sudo apt install paros
sudo apt install parted
sudo apt install pasco
sudo apt install passing-the-hash
sudo apt install passwd
sudo apt install patator
sudo apt install patch
sudo apt install pciutils
sudo apt install pcsc-tools
sudo apt install pcscd
sudo apt install pdf-parser
sudo apt install pdfid
sudo apt install pdgmail
sudo apt install perl
sudo apt install perl-base
sudo apt install perl-cisco-copyconfig
sudo apt install perl-modules-5.26
sudo apt install perl-openssl-defaults:amd64
sudo apt install perl-tk
sudo apt install pev
sudo apt install php
sudo apt install php-common
sudo apt install php-mysql
sudo apt install php7.0
sudo apt install php7.0-cli
sudo apt install php7.0-common
sudo apt install php7.0-json
sudo apt install php7.0-mysql
sudo apt install php7.0-opcache
sudo apt install php7.0-readline
sudo apt install pinentry-gnome3
sudo apt install pipal
sudo apt install pixiewps
sudo apt install plecost
sudo apt install pocl-opencl-icd
sudo apt install polenum
sudo apt install policycoreutils
sudo apt install policykit-1
sudo apt install poppler-data
sudo apt install poppler-utils
sudo apt install postgresql
sudo apt install postgresql-10
sudo apt install postgresql-client-10
sudo apt install postgresql-client-common
sudo apt install postgresql-common
sudo apt install powerfuzzer
sudo apt install powermgmt-base
sudo apt install powersploit
sudo apt install ppp
sudo apt install preview-latex-style
sudo apt install procps
sudo apt install proj-bin
sudo apt install proj-data
sudo apt install protos-sip
sudo apt install proxychains
sudo apt install proxystrike
sudo apt install proxytunnel
sudo apt install psmisc
sudo apt install pst-utils
sudo apt install ptunnel
sudo apt install pulseaudio
sudo apt install pulseaudio-module-bluetooth
sudo apt install pulseaudio-utils
sudo apt install pwgen
sudo apt install pwnat
sudo apt install pyrit
sudo apt install python
sudo apt install python-adns
sudo apt install python-aes
sudo apt install python-all
sudo apt install python-all-dev
sudo apt install python-anyjson
sudo apt install python-apt-common
sudo apt install python-argcomplete
sudo apt install python-asn1crypto
sudo apt install python-attr
sudo apt install python-automat
sudo apt install python-backports-abc
sudo apt install python-backports-shutil-get-terminal-size
sudo apt install python-backports.ssl-match-hostname
sudo apt install python-beautifulsoup
sudo apt install python-blinker
sudo apt install python-bs4
sudo apt install python-bson
sudo apt install python-bson-ext
sudo apt install python-cairo:amd64
sudo apt install python-capstone
sudo apt install python-certifi
sudo apt install python-cffi-backend
sudo apt install python-chardet
sudo apt install python-click
sudo apt install python-colorama
sudo apt install python-concurrent.futures
sudo apt install python-configargparse
sudo apt install python-configobj
sudo apt install python-configparser
sudo apt install python-constantly
sudo apt install python-construct
sudo apt install python-couchdbkit
sudo apt install python-crypto
sudo apt install python-cryptography
sudo apt install python-cycler
sudo apt install python-dateutil
sudo apt install python-dbus
sudo apt install python-decorator
sudo apt install python-dev
sudo apt install python-dicttoxml
sudo apt install python-distorm3
sudo apt install python-dns
sudo apt install python-dnslib
sudo apt install python-dnspython
sudo apt install python-docutils
sudo apt install python-easygui
sudo apt install python-egenix-mxdatetime
sudo apt install python-egenix-mxtools
sudo apt install python-elixir
sudo apt install python-enchant
sudo apt install python-enum34
sudo apt install python-faraday
sudo apt install python-feedparser
sudo apt install python-flask
sudo apt install python-functools32
sudo apt install python-fuse
sudo apt install python-future
sudo apt install python-gdal
sudo apt install python-geoip
sudo apt install python-gevent
sudo apt install python-gi
sudo apt install python-glade2
sudo apt install python-gobject
sudo apt install python-gobject-2
sudo apt install python-greenlet
sudo apt install python-gridfs
sudo apt install python-gtk2
sudo apt install python-gtkspellcheck
sudo apt install python-h2
sudo apt install python-hpack
sudo apt install python-html2text
sudo apt install python-html5lib
sudo apt install python-http-parser
sudo apt install python-httplib2
sudo apt install python-httpretty
sudo apt install python-hyperframe
sudo apt install python-hyperlink
sudo apt install python-idna
sudo apt install python-imaging
sudo apt install python-impacket
sudo apt install python-incremental
sudo apt install python-ipaddress
sudo apt install python-ipy
sudo apt install python-ipython
sudo apt install python-ipython-genutils
sudo apt install python-itsdangerous
sudo apt install python-jdcal
sudo apt install python-jinja2
sudo apt install python-jsbeautifier
sudo apt install python-jsonpickle
sudo apt install python-jsonrpclib
sudo apt install python-jwt
sudo apt install python-keyring
sudo apt install python-keyrings.alt
sudo apt install python-ldb:amd64
sudo apt install python-levenshtein
sudo apt install python-libxml2
sudo apt install python-libxslt1
sudo apt install python-lxml
sudo apt install python-m2crypto
sudo apt install python-mako
sudo apt install python-markupsafe
sudo apt install python-matplotlib
sudo apt install python-matplotlib-data
sudo apt install python-mechanize
sudo apt install python-metaconfig
sudo apt install python-minimal
sudo apt install python-mockito
sudo apt install python-mpltoolkits.basemap-data
sudo apt install python-msgpack
sudo apt install python-mysqldb
sudo apt install python-nassl
sudo apt install python-netaddr
sudo apt install python-numpy
sudo apt install python-olefile
sudo apt install python-openpyxl
sudo apt install python-openssl
sudo apt install python-pam
sudo apt install python-paramiko
sudo apt install python-passlib
sudo apt install python-pathlib2
sudo apt install python-pcapy
sudo apt install python-peepdf
sudo apt install python-pefile
sudo apt install python-pexpect
sudo apt install python-pickleshare
sudo apt install python-pil:amd64
sudo apt install python-pil.imagetk:amd64
sudo apt install python-pip
sudo apt install python-pip-whl
sudo apt install python-pkg-resources
sudo apt install python-prettytable
sudo apt install python-prompt-toolkit
sudo apt install python-psycopg2
sudo apt install python-ptyprocess
sudo apt install python-py
sudo apt install python-pyasn1
sudo apt install python-pyasn1-modules
sudo apt install python-pycurl
sudo apt install python-pygments
sudo apt install python-pyinotify
sudo apt install python-pymongo
sudo apt install python-pymongo-ext
sudo apt install python-pymssql
sudo apt install python-pyparsing
sudo apt install python-pypdf2
sudo apt install python-pyperclip
sudo apt install python-pyscard
sudo apt install python-pyside.qtcore
sudo apt install python-pyside.qtgui
sudo apt install python-pyside.qtnetwork
sudo apt install python-pyside.qtwebkit
sudo apt install python-pysnmp4
sudo apt install python-pysnmp4-apps
sudo apt install python-pysnmp4-mibs
sudo apt install python-pyspatialite
sudo apt install python-pysqlite2
sudo apt install python-pytest
sudo apt install python-pyx
sudo apt install python-qgis
sudo apt install python-qgis-common
sudo apt install python-qrcode
sudo apt install python-qscintilla2
sudo apt install python-qt4
sudo apt install python-qt4-sql
sudo apt install python-requests
sudo apt install python-restkit
sudo apt install python-rfidiot
sudo apt install python-roman
sudo apt install python-samba
sudo apt install python-scandir
sudo apt install python-scapy
sudo apt install python-secretstorage
sudo apt install python-serial
sudo apt install python-service-identity
sudo apt install python-setuptools
sudo apt install python-shapely
sudo apt install python-simplegeneric
sudo apt install python-simplejson
sudo apt install python-singledispatch
sudo apt install python-sip
sudo apt install python-six
sudo apt install python-slowaes
sudo apt install python-socketpool
sudo apt install python-socks
sudo apt install python-sqlalchemy
sudo apt install python-sqlalchemy-ext
sudo apt install python-subprocess32
sudo apt install python-talloc
sudo apt install python-tdb
sudo apt install python-tk
sudo apt install python-tornado
sudo apt install python-traitlets
sudo apt install python-twisted
sudo apt install python-twisted-bin:amd64
sudo apt install python-twisted-core
sudo apt install python-twisted-web
sudo apt install python-typing
sudo apt install python-tz
sudo apt install python-unicodecsv
sudo apt install python-urllib3
sudo apt install python-urwid
sudo apt install python-usb
sudo apt install python-utidylib
sudo apt install python-wcwidth
sudo apt install python-webencodings
sudo apt install python-webunit
sudo apt install python-werkzeug
sudo apt install python-wheel
sudo apt install python-whoosh
sudo apt install python-wxgtk3.0
sudo apt install python-wxtools
sudo apt install python-wxversion
sudo apt install python-xdg
sudo apt install python-xlsxwriter
sudo apt install python-xmlbuilder
sudo apt install python-yaml
sudo apt install python-yara
sudo apt install python-zope.interface
sudo apt install python2.7
sudo apt install python2.7-dev
sudo apt install python2.7-minimal
sudo apt install python3
sudo apt install python3-advancedhttpserver
sudo apt install python3-alembic
sudo apt install python3-apt
sudo apt install python3-argcomplete
sudo apt install python3-argh
sudo apt install python3-asn1crypto
sudo apt install python3-binwalk
sudo apt install python3-blinker
sudo apt install python3-boltons
sudo apt install python3-brlapi
sudo apt install python3-brotli
sudo apt install python3-cairo:amd64
sudo apt install python3-certifi
sudo apt install python3-cffi-backend
sudo apt install python3-chardet
sudo apt install python3-click
sudo apt install python3-colorama
sudo apt install python3-construct
sudo apt install python3-crcelk
sudo apt install python3-cryptography
sudo apt install python3-cssutils
sudo apt install python3-cups
sudo apt install python3-cupshelpers
sudo apt install python3-cycler
sudo apt install python3-dateutil
sudo apt install python3-dbus
sudo apt install python3-debconf
sudo apt install python3-debian
sudo apt install python3-debianbts
sudo apt install python3-decorator
sudo apt install python3-distutils
sudo apt install python3-dnspython
sudo apt install python3-editor
sudo apt install python3-feedparser
sudo apt install python3-flask
sudo apt install python3-geoip2
sudo apt install python3-geojson
sudo apt install python3-gi
sudo apt install python3-gi-cairo
sudo apt install python3-graphene
sudo apt install python3-graphene-sqlalchemy
sudo apt install python3-graphql-core
sudo apt install python3-graphql-relay
sudo apt install python3-h2
sudo apt install python3-hpack
sudo apt install python3-html2text
sudo apt install python3-httplib2
sudo apt install python3-hyperframe
sudo apt install python3-icalendar
sudo apt install python3-idna
sudo apt install python3-iso8601
sudo apt install python3-itsdangerous
sudo apt install python3-jinja2
sudo apt install python3-jsbeautifier
sudo apt install python3-kaitaistruct
sudo apt install python3-lib2to3
sudo apt install python3-louis
sudo apt install python3-mako
sudo apt install python3-markupsafe
sudo apt install python3-matplotlib
sudo apt install python3-maxminddb
sudo apt install python3-minimal
sudo apt install python3-mpltoolkits.basemap
sudo apt install python3-msgpack
sudo apt install python3-numpy
sudo apt install python3-olefile
sudo apt install python3-opengl
sudo apt install python3-openssl
sudo apt install python3-pampy
sudo apt install python3-paramiko
sudo apt install python3-passlib
sudo apt install python3-pathtools
sudo apt install python3-pil:amd64
sudo apt install python3-pkg-resources
sudo apt install python3-pluginbase
sudo apt install python3-promise
sudo apt install python3-psycopg2
sudo apt install python3-pyasn1
sudo apt install python3-pyatspi
sudo apt install python3-pycurl
sudo apt install python3-pyinotify
sudo apt install python3-pyotp
sudo apt install python3-pyparsing
sudo apt install python3-pyperclip
sudo apt install python3-pyqt4
sudo apt install python3-pyqtgraph
sudo apt install python3-pysimplesoap
sudo apt install python3-reportbug
sudo apt install python3-requests
sudo apt install python3-ruamel.yaml
sudo apt install python3-scipy
sudo apt install python3-serial
sudo apt install python3-simplejson
sudo apt install python3-singledispatch
sudo apt install python3-sip
sudo apt install python3-six
sudo apt install python3-smbc
sudo apt install python3-smoke-zephyr
sudo apt install python3-software-properties
sudo apt install python3-sortedcontainers
sudo apt install python3-speechd
sudo apt install python3-sqlalchemy
sudo apt install python3-tabulate
sudo apt install python3-termcolor
sudo apt install python3-tk:amd64
sudo apt install python3-tornado
sudo apt install python3-tz
sudo apt install python3-tzlocal
sudo apt install python3-urllib3
sudo apt install python3-urwid
sudo apt install python3-watchdog
sudo apt install python3-websocket
sudo apt install python3-werkzeug
sudo apt install python3-xdg
sudo apt install python3-xlsxwriter
sudo apt install python3-yaml
sudo apt install python3.6
sudo apt install python3.6-minimal
sudo apt install qdbus
sudo apt install qemu
sudo apt install qemu-efi
sudo apt install qemu-efi-aarch64
sudo apt install qemu-slof
sudo apt install qemu-system
sudo apt install qemu-system-arm
sudo apt install qemu-system-common
sudo apt install qemu-system-mips
sudo apt install qemu-system-misc
sudo apt install qemu-system-ppc
sudo apt install qemu-system-sparc
sudo apt install qemu-system-x86
sudo apt install qemu-user
sudo apt install qemu-user-static
sudo apt install qemu-utils
sudo apt install qt-at-spi:amd64
sudo apt install qt4-designer
sudo apt install qt4-linguist-tools
sudo apt install qt4-qmake
sudo apt install qt5-gtk-platformtheme:amd64
sudo apt install qtchooser
sudo apt install qtcore4-l10n
sudo apt install qttranslations5-l10n
sudo apt install radare2
sudo apt install rainbowcrack
sudo apt install rake
sudo apt install rcracki-mt
sudo apt install rdesktop
sudo apt install read-edid
sudo apt install readline-common
sudo apt install readpst
sudo apt install realmd
sudo apt install reaver
sudo apt install rebind
sudo apt install recon-ng
sudo apt install recordmydesktop
sudo apt install recoverjpeg
sudo apt install redfang
sudo apt install redis-server
sudo apt install redis-tools
sudo apt install redsocks
sudo apt install reglookup
sudo apt install regripper
sudo apt install reportbug
sudo apt install responder
sudo apt install rfkill
sudo apt install rifiuti
sudo apt install rifiuti2
sudo apt install rsmangler
sudo apt install rsync
sudo apt install rsyslog
sudo apt install rtkit
sudo apt install rtpbreak
sudo apt install rtpflood
sudo apt install rtpinsertsound
sudo apt install rtpmixsound
sudo apt install ruby
sudo apt install ruby-addressable
sudo apt install ruby-ansi
sudo apt install ruby-atomic
sudo apt install ruby-buftok
sudo apt install ruby-bundler
sudo apt install ruby-celluloid
sudo apt install ruby-celluloid-io
sudo apt install ruby-daemons
sudo apt install ruby-dataobjects
sudo apt install ruby-dataobjects-mysql
sudo apt install ruby-dataobjects-postgres
sudo apt install ruby-dataobjects-sqlite3
sudo apt install ruby-dev:amd64
sudo apt install ruby-did-you-mean
sudo apt install ruby-diff-lcs
sudo apt install ruby-dm-core
sudo apt install ruby-dm-do-adapter
sudo apt install ruby-dm-migrations
sudo apt install ruby-dm-serializer
sudo apt install ruby-dm-sqlite-adapter
sudo apt install ruby-docile
sudo apt install ruby-domain-name
sudo apt install ruby-em-websocket
sudo apt install ruby-equalizer
sudo apt install ruby-erubis
sudo apt install ruby-ethon
sudo apt install ruby-eventmachine
sudo apt install ruby-execjs
sudo apt install ruby-faraday
sudo apt install ruby-ffi
sudo apt install ruby-geoip
sudo apt install ruby-hitimes
sudo apt install ruby-http
sudo apt install ruby-http-cookie
sudo apt install ruby-http-form-data
sudo apt install ruby-http-parser.rb
sudo apt install ruby-httpclient
sudo apt install ruby-json
sudo apt install ruby-librex
sudo apt install ruby-libv8
sudo apt install ruby-memoizable
sudo apt install ruby-mime
sudo apt install ruby-mime-types
sudo apt install ruby-mime-types-data
sudo apt install ruby-mini-exiftool
sudo apt install ruby-minitest
sudo apt install ruby-mojo-magick
sudo apt install ruby-molinillo
sudo apt install ruby-msfrpc-client
sudo apt install ruby-msgpack
sudo apt install ruby-multi-json
sudo apt install ruby-multipart-post
sudo apt install ruby-naught
sudo apt install ruby-net-http-digest-auth
sudo apt install ruby-net-http-persistent
sudo apt install ruby-net-telnet
sudo apt install ruby-nio4r
sudo apt install ruby-nokogiri
sudo apt install ruby-oj
sudo apt install ruby-parseconfig
sudo apt install ruby-pkg-config
sudo apt install ruby-power-assert
sudo apt install ruby-public-suffix
sudo apt install ruby-qr4r
sudo apt install ruby-rack
sudo apt install ruby-rack-protection
sudo apt install ruby-rchardet
sudo apt install ruby-ref
sudo apt install ruby-rqrcode
sudo apt install ruby-rspec-expectations
sudo apt install ruby-rspec-support
sudo apt install ruby-ruby-progressbar
sudo apt install ruby-rubydns
sudo apt install ruby-simple-oauth
sudo apt install ruby-simplecov
sudo apt install ruby-simplecov-html
sudo apt install ruby-sinatra
sudo apt install ruby-snmp
sudo apt install ruby-spider
sudo apt install ruby-sqlite3
sudo apt install ruby-term-ansicolor
sudo apt install ruby-terminal-table
sudo apt install ruby-test-unit
sudo apt install ruby-therubyracer
sudo apt install ruby-thor
sudo apt install ruby-thread-safe
sudo apt install ruby-tilt
sudo apt install ruby-timers
sudo apt install ruby-tins
sudo apt install ruby-twitter
sudo apt install ruby-typhoeus
sudo apt install ruby-uglifier
sudo apt install ruby-unf
sudo apt install ruby-unf-ext
sudo apt install ruby-unicode-display-width
sudo apt install ruby-yajl
sudo apt install ruby-zip
sudo apt install ruby2.3
sudo apt install ruby2.3-dev:amd64
sudo apt install rubygems-integration
sudo apt install rwho
sudo apt install rwhod
sudo apt install rygel
sudo apt install safecopy
sudo apt install sakis3g
sudo apt install samba
sudo apt install samba-common
sudo apt install samba-common-bin
sudo apt install samba-dsdb-modules
sudo apt install samba-libs:amd64
sudo apt install samba-vfs-modules
sudo apt install samdump2
sudo apt install sane-utils
sudo apt install sbd
sudo apt install scalpel
sudo apt install screen
sudo apt install scrounge-ntfs
sudo apt install sctpscan
sudo apt install seabios
sudo apt install sed
sudo apt install selinux-utils
sudo apt install sendemail
sudo apt install sensible-utils
sudo apt install set
sudo apt install sfuzz
sudo apt install sgml-base
sudo apt install shared-mime-info
sudo apt install sidguesser
sudo apt install siege
sudo apt install siparmyknife
sudo apt install sipcrack
sudo apt install sipp
sudo apt install sipvicious
sudo apt install skipfish
sudo apt install sleuthkit
sudo apt install smali
sudo apt install smartmontools
sudo apt install smbclient
sudo apt install smbmap
sudo apt install smitools
sudo apt install smtp-user-enum
sudo apt install sniffjoke
sudo apt install snmp
sudo apt install snmpcheck
sudo apt install snmpd
sudo apt install sntp
sudo apt install socat
sudo apt install software-properties-common
sudo apt install software-properties-gtk
sudo apt install sound-icons
sudo apt install sound-theme-freedesktop
sudo apt install sparta
sudo apt install spectools
sudo apt install speech-dispatcher
sudo apt install speech-dispatcher-audio-plugins:amd64
sudo apt install speech-dispatcher-espeak-ng
sudo apt install spike
sudo apt install spooftooph
sudo apt install sqldict
sudo apt install sqlite3
sudo apt install sqlitebrowser
sudo apt install sqlmap
sudo apt install sqlninja
sudo apt install sqlsus
sudo apt install sqsh
sudo apt install squashfs-tools
sudo apt install ssl-cert
sudo apt install sslcaudit
sudo apt install ssldump
sudo apt install sslh
sudo apt install sslscan
sudo apt install sslsniff
sudo apt install sslsplit
sudo apt install sslstrip
sudo apt install sslyze
sudo apt install statsprocessor
sudo apt install stunnel4
sudo apt install subversion
sudo apt install suckless-tools
sudo apt install sucrack
sudo apt install sudo
sudo apt install swaks
sudo apt install switcheroo-control
sudo apt install sysstat
sudo apt install system-config-printer-common
sudo apt install system-config-printer-udev
sudo apt install systemd
sudo apt install systemd-sysv
sudo apt install sysvinit-utils
sudo apt install t1utils
sudo apt install t50
sudo apt install tar
sudo apt install tasksel
sudo apt install tasksel-data
sudo apt install tcl
sudo apt install tcl-expect:amd64
sudo apt install tcl8.6
sudo apt install tcpdump
sudo apt install tcpflow
sudo apt install tcpick
sudo apt install tcpreplay
sudo apt install tcpwatch-httpproxy
sudo apt install tdb-tools
sudo apt install telnet
sudo apt install termineter
sudo apt install testdisk
sudo apt install tex-common
sudo apt install tex-gyre
sudo apt install texlive-base
sudo apt install texlive-binaries
sudo apt install texlive-fonts-recommended
sudo apt install texlive-latex-base
sudo apt install texlive-latex-base-doc
sudo apt install texlive-latex-extra
sudo apt install texlive-latex-recommended
sudo apt install texlive-pictures
sudo apt install texlive-plain-generic
sudo apt install tftp
sudo apt install tftpd32
sudo apt install thc-ipv6
sudo apt install thc-pptp-bruter
sudo apt install thc-ssl-dos
sudo apt install theharvester
sudo apt install thin
sudo apt install thin-provisioning-tools
sudo apt install tightvncserver
sudo apt install tipa
sudo apt install tk
sudo apt install tk8.5
sudo apt install tk8.6
sudo apt install tk8.6-blt2.5
sudo apt install tlssled
sudo apt install tmux
sudo apt install tnscmd10g
sudo apt install totem
sudo apt install totem-common
sudo apt install totem-plugins
sudo apt install traceroute
sudo apt install tracker
sudo apt install tracker-extract
sudo apt install tracker-miner-fs
sudo apt install truecrack
sudo apt install tshark
sudo apt install ttf-bitstream-vera
sudo apt install twofi
sudo apt install tzdata
sudo apt install u3-pwn
sudo apt install u3-tool
sudo apt install ua-tester
sudo apt install ucf
sudo apt install udev
sudo apt install udisks2
sudo apt install udptunnel
sudo apt install unattended-upgrades
sudo apt install unicorn-magic
sudo apt install unicornscan
sudo apt install uniscan
sudo apt install unix-privesc-check
sudo apt install unrar
sudo apt install unzip
sudo apt install update-inetd
sudo apt install upower
sudo apt install upx-ucl
sudo apt install urlcrazy
sudo apt install usb-modeswitch
sudo apt install usb-modeswitch-data
sudo apt install usbmuxd
sudo apt install usbutils
sudo apt install util-linux
sudo apt install uuid-runtime
sudo apt install va-driver-all:amd64
sudo apt install vboot-kernel-utils
sudo apt install vboot-utils
sudo apt install vdpau-driver-all:amd64
sudo apt install vim
sudo apt install vim-common
sudo apt install vim-gtk
sudo apt install vim-gui-common
sudo apt install vim-runtime
sudo apt install vim-tiny
sudo apt install vinetto
sudo apt install vino
sudo apt install virtualbox-guest-dkms
sudo apt install virtualbox-guest-utils
sudo apt install virtualbox-guest-x11
sudo apt install vlan
sudo apt install voiphopper
sudo apt install volafox
sudo apt install volatility
sudo apt install volatility-tools
sudo apt install vpnc
sudo apt install vpnc-scripts
sudo apt install wafw00f
sudo apt install wamerican
sudo apt install wapiti
sudo apt install wce
sudo apt install webacoo
sudo apt install webscarab
sudo apt install webshells
sudo apt install weevely
sudo apt install wfuzz
sudo apt install wget
sudo apt install whatweb
sudo apt install whiptail
sudo apt install whois
sudo apt install wifi-honey
sudo apt install wifitap
sudo apt install wifite
sudo apt install windows-binaries
sudo apt install wine
sudo apt install wine64
sudo apt install winexe
sudo apt install wireless-regdb
sudo apt install wireless-tools
sudo apt install wireshark
sudo apt install wireshark-common
sudo apt install wireshark-qt
sudo apt install wol-e
sudo apt install wordlists
sudo apt install wpasupplicant
sudo apt install wpscan
sudo apt install x11-apps
sudo apt install x11-common
sudo apt install x11-utils
sudo apt install x11-xkb-utils
sudo apt install x11-xserver-utils
sudo apt install x11proto-core-dev
sudo apt install x11proto-damage-dev
sudo apt install x11proto-dri2-dev
sudo apt install x11proto-fixes-dev
sudo apt install x11proto-gl-dev
sudo apt install x11proto-input-dev
sudo apt install x11proto-kb-dev
sudo apt install x11proto-xext-dev
sudo apt install x11proto-xf86vidmode-dev
sudo apt install xauth
sudo apt install xbitmaps
sudo apt install xbrlapi
sudo apt install xclip
sudo apt install xdg-user-dirs
sudo apt install xdg-utils
sudo apt install xfonts-base
sudo apt install xfonts-encodings
sudo apt install xfonts-utils
sudo apt install xinetd
sudo apt install xkb-data
sudo apt install xml-core
sudo apt install xorg-sgml-doctools
sudo apt install xpdf
sudo apt install xprobe
sudo apt install xserver-common
sudo apt install xserver-xephyr
sudo apt install xserver-xorg
sudo apt install xserver-xorg-core
sudo apt install xserver-xorg-input-all
sudo apt install xserver-xorg-input-libinput
sudo apt install xserver-xorg-input-wacom
sudo apt install xserver-xorg-legacy
sudo apt install xserver-xorg-video-all
sudo apt install xserver-xorg-video-amdgpu
sudo apt install xserver-xorg-video-ati
sudo apt install xserver-xorg-video-fbdev
sudo apt install xserver-xorg-video-intel
sudo apt install xserver-xorg-video-nouveau
sudo apt install xserver-xorg-video-qxl
sudo apt install xserver-xorg-video-radeon
sudo apt install xserver-xorg-video-vesa
sudo apt install xserver-xorg-video-vmware
sudo apt install xsltproc
sudo apt install xspy
sudo apt install xsser
sudo apt install xterm
sudo apt install xtightvncviewer
sudo apt install xtrans-dev
sudo apt install xwayland
sudo apt install xxd
sudo apt install xz-utils
sudo apt install yelp
sudo apt install yelp-xsl
sudo apt install yersinia
sudo apt install zaproxy
sudo apt install zeitgeist-core
sudo apt install zenity
sudo apt install zenity-common
sudo apt install zenmap
sudo apt install zerofree
sudo apt install zim
sudo apt install zip
sudo apt install zlib1g:amd64
sudo apt install zsh
sudo apt install zsh-common
